const fs=require('node:fs/promises'),path=require('node:path'),crypto=require('node:crypto')
const {createCalDAVClient}=require('./caldav-client.cjs'),{createSchedulePrivateStore}=require('./schedule-private.cjs'),{scheduleURL}=require('./schedule-network.cjs'),{nextDue}=require('./schedule-refresh.cjs')
const sha=value=>crypto.createHash('sha256').update(value).digest('hex')
function installCalDAVIPC({ipcMain,dialog,win,app,safeStorage,gateway,readDatabase,assertFrame,refreshScheduler,qaLoopback=false}){
  let ready=null;const clients=new Map(),discoveries=new Map(),writeBindings=new Map(),busy=new Set(),removers=new Map()
  const send=(channel,value)=>{if(!win.isDestroyed())win.webContents.send(channel,value)}
  async function context(record){const settings=await readDatabase(win,'settings','main'),dataset=await readDatabase(win,'datasetState','main'),state=await readDatabase(win,'calendarRules','main');if(!settings||dataset&&dataset.mode!=='active'||record&&record.revoked||record&&(record.ownerId!==settings.profileId||record.datasetId!==settings.datasetId||record.policyEpoch!==(settings.changePolicy?.epoch??0)))throw new Error('CALDAV_AUTHORITY_CHANGED');if(settings.changePolicy?.stops?.routines)throw new Error('CALDAV_ROUTINES_STOPPED');if(record){const source=state?.sources?.find(row=>row.id===record.sourceId);if(!source?.ics||source.ics.retentionUntil&&source.ics.retentionUntil<=new Date().toISOString())throw new Error('CALDAV_SOURCE_PERMISSION_EXPIRED')}return {settings,state}}
  function status(record){return {id:record.id,sourceId:record.sourceId,format:'caldav',kind:'url',displayName:new URL(record.url).origin,refreshPolicy:record.refreshPolicy,lastCheckedAt:record.lastCheckedAt,lastChangedAt:record.lastChangedAt,nextDueAt:record.nextDueAt,lastError:record.lastError,status:record.status,bodySha256:record.lastBodySha256,qaFixture:record.qaFixture,readTitle:record.readTitle,writeTitle:record.writeTitle,writeEnabled:Boolean(record.writeCollection)}}
  async function sweep(record){try{await context(record);await gateway.assertAllowed('caldav');if(record.pendingCandidate&&Date.parse(record.pendingCandidate.fetchedAt)+86400000<=Date.now()){delete record.pendingCandidate;clients.delete(record.id)}return true}catch{delete record.pendingCandidate;clients.delete(record.id);if(record.status!=='paused'){record.status='paused';record.lastError='取得を設定・資料の許可により停止しています';send('michi:schedule-refresh-status',status(record))}return false}}
  function client(record){if(!clients.has(record.id)){gateway.authorizeScheduleOrigin('caldav',new URL(record.url).origin);const current=createCalDAVClient({...record,qaLoopback,fetchImpl:async(url,init)=>{await context(record);return gateway.fetch('caldav',url,init)}});current.selectCollections(record.readCollection,record.writeCollection,Boolean(record.writeCollection));clients.set(record.id,current)}return clients.get(record.id)}
  async function load(){ready??=(async()=>{const root=await fs.realpath(app.getPath('userData')),store=await createSchedulePrivateStore({directory:path.join(root,'caldav-private'),safeStorage}),value=await store.load(),scheduler=await refreshScheduler.getService();for(const record of value.caldav)removers.set(record.id,scheduler.addJob(record.id,{sweep:()=>sweep(record),due:now=>record.refreshPolicy!=='manual'&&record.nextDueAt&&Date.parse(record.nextDueAt)<=now,run:()=>sync(record.id)}));return {store,value,scheduler}})().catch(error=>{ready=null;throw error});return ready}
  async function account(id){const {value}=await load(),record=value.caldav.find(row=>row.id===id);if(!record)throw new Error('CALDAV_ACCOUNT_MISSING');await context(record);return record}
  async function sync(id){const {store,value}=await load(),record=value.caldav.find(row=>row.id===id);if(!record)throw new Error('CALDAV_ACCOUNT_MISSING');if(busy.has(id))return {changed:false,...status(record)};busy.add(id)
    try{const {state}=await context(record),source=state.sources.find(row=>row.id===record.sourceId),from=source.coverageFrom.replaceAll('-','')+'T000000Z',to=new Date(Date.parse(source.coverageTo+'T00:00:00Z')+86400000).toISOString().slice(0,10).replaceAll('-','')+'T000000Z',result=await client(record).sync(record.mirror,from,to);await context(record)
      const deleted=new Map((record.pendingDeleted??[]).map(row=>[row.href,row]));for(const row of result.deleted)deleted.set(row.href,row);for(const row of result.objects)deleted.delete(row.href)
      const payload={version:1,collection:result.collection,objects:result.objects.map(({href,etag,data})=>({href,etag,data})).sort((a,b)=>a.href.localeCompare(b.href)),deleted:[...deleted.values()].sort((a,b)=>a.href.localeCompare(b.href))},semantic=sha(JSON.stringify({...payload,objects:payload.objects.map(({href,data})=>({href,data}))})),bytes=Buffer.from(JSON.stringify(payload)),bodySha256=sha(bytes),changed=record.semanticSha256!==semantic||(record.awaitingApproval||record.status==='pending')&&!record.pendingCandidate
      if(bytes.length>1048576)throw new Error('CALDAV_MIRROR_BUDGET')
      record.mirror={token:result.token,objects:result.objects.map(({href,etag})=>({href,etag}))};record.pendingDeleted=payload.deleted;record.lastCheckedAt=result.checkedAt;record.lastError=null;record.failures=0;record.nextDueAt=nextDue(record,Date.now())
      if(changed){record.semanticSha256=semantic;record.lastBodySha256=bodySha256;record.lastChangedAt=result.checkedAt;record.status='pending';record.awaitingApproval=true;record.pendingCandidate={ownerId:record.ownerId,datasetId:record.datasetId,policyEpoch:record.policyEpoch,subscriptionId:id,sourceId:record.sourceId,format:'caldav',fetchedAt:result.checkedAt,bodySha256,bytes:new Uint8Array(bytes),qaFixture:record.qaFixture};send('michi:schedule-refresh-changed',record.pendingCandidate)}
      else if(record.status!=='pending')record.status='current'
      const saved=structuredClone(value);for(const row of saved.caldav)delete row.pendingCandidate;await store.save(saved);send('michi:schedule-refresh-status',status(record));return {changed,...status(record)}
    }catch(error){delete record.pendingCandidate;clients.delete(id);const paused=/AUTHORITY_CHANGED|ROUTINES_STOPPED|SOURCE_PERMISSION_EXPIRED|NETWORK_POLICY_OFFLINE/.test(error?.code??error?.message??'');record.status=paused?'paused':'stale';record.lastError=paused?'取得を設定・資料の許可により停止しています':'CalDAVの取得に失敗しました。資料は古い可能性があります';record.lastCheckedAt=new Date().toISOString();record.failures=Math.min(10,(record.failures??0)+1);record.nextDueAt=new Date(Date.now()+Math.max(error.retryAfter??0,Math.min(3600000,30000*2**(record.failures-1)))).toISOString();if(paused){clients.delete(id);delete record.pendingCandidate;}const saved=structuredClone(value);for(const row of saved.caldav)delete row.pendingCandidate;await store.save(saved);send('michi:schedule-refresh-status',status(record));return {changed:false,...status(record)}}finally{busy.delete(id)}
  }
  ipcMain.handle('michi:caldav',async(event,request)=>{
    assertFrame(event);const current=await context(),action=request?.action,keys=['list','start'].includes(action)?['action']:action==='discover'?['action','url','username','password']:action==='configure'?['action','discoveryId','sourceId','readCollection','writeCollection','dedicatedConfirmed','refreshPolicy']:action==='prepare-write'?['action','id','eventId','operation']:action==='apply-write'?['action','id','token']:action==='acknowledge'?['action','id','bodySha256']:['action','id']
    if(!request||typeof request!=='object'||Array.isArray(request)||Object.keys(request).length!==keys.length||keys.some(key=>!Object.hasOwn(request,key)))throw new Error('CALDAV_REQUEST_INVALID')
    const {store,value,scheduler}=await load();for(const [id,row] of discoveries)if(row.expiresAt<=Date.now())discoveries.delete(id)
    if(action==='list'||action==='start'){if(action==='start')scheduler.start();return value.caldav.filter(row=>row.ownerId===current.settings.profileId&&row.datasetId===current.settings.datasetId).map(status)}
    if(action==='discover'){
      const target=scheduleURL(request.url,qaLoopback);await gateway.assertAllowed('caldav');const consent=await dialog.showMessageBox(win,{type:'question',title:'CalDAVの読取先を許可',message:`${target.origin} のカレンダー一覧を取得します`,detail:'入力したユーザー名とアプリ専用パスワードをこの接続先だけに使用します。予定の読取先・書込先は別途選びます。',buttons:['一覧を取得','取消'],defaultId:1,cancelId:1,noLink:true});if(consent.response!==0)return null
      const latest=await context();if(latest.settings.profileId!==current.settings.profileId||latest.settings.datasetId!==current.settings.datasetId||(latest.settings.changePolicy?.epoch??0)!==(current.settings.changePolicy?.epoch??0))throw new Error('CALDAV_AUTHORITY_CHANGED');gateway.authorizeScheduleOrigin('caldav',target.origin)
      const candidate={url:request.url,username:request.username,password:request.password,ownerId:current.settings.profileId,datasetId:current.settings.datasetId,policyEpoch:current.settings.changePolicy?.epoch??0},inspection=createCalDAVClient({...candidate,qaLoopback,fetchImpl:async(url,init)=>{const latest=await context();if(latest.settings.profileId!==candidate.ownerId||latest.settings.datasetId!==candidate.datasetId||(latest.settings.changePolicy?.epoch??0)!==candidate.policyEpoch)throw new Error('CALDAV_AUTHORITY_CHANGED');return gateway.fetch('caldav',url,init)}}),collections=await inspection.discover(),id=crypto.randomUUID();if(discoveries.size>20)discoveries.clear();discoveries.set(id,{...candidate,collections,expiresAt:Date.now()+600000});return {id,collections,qaFixture:target.protocol==='http:'}
    }
    if(action==='configure'){
      const discovery=discoveries.get(request.discoveryId);if(!discovery||discovery.expiresAt<=Date.now()||discovery.ownerId!==current.settings.profileId||discovery.datasetId!==current.settings.datasetId||discovery.policyEpoch!==(current.settings.changePolicy?.epoch??0))throw new Error('CALDAV_DISCOVERY_EXPIRED')
      const read=discovery.collections.find(row=>row.href===request.readCollection),write=discovery.collections.find(row=>row.href===request.writeCollection),source=current.state?.sources?.find(row=>row.id===request.sourceId)
      if(!read||request.writeCollection!==null&&(!write||write.href===read.href||request.dedicatedConfirmed!==true)||!['manual','daily','weekly','window_dense'].includes(request.refreshPolicy)||!source?.ics||!source.caldav&&source.ics.components.length>0||value.caldav.length>=20||value.caldav.some(row=>row.sourceId===source.id&&row.ownerId===current.settings.profileId&&row.datasetId===current.settings.datasetId))throw new Error('CALDAV_CONFIGURATION_INVALID')
      const consent=await dialog.showMessageBox(win,{type:'question',title:'CalDAVの対象を登録',message:`読取：${read.title}\n書込：${write?.title??'未登録・書込しない'}`,detail:'書込先はアプリ専用に選んだ別のカレンダーだけです。書込のたびに差分を確認します。端末内の編集だけでは外部に書き込みません。',buttons:['対象を登録','取消'],defaultId:1,cancelId:1,noLink:true});if(consent.response!==0)return null;await context({...discovery,sourceId:source.id})
      const record={id:crypto.randomUUID(),sourceId:source.id,url:discovery.url,username:discovery.username,password:discovery.password,ownerId:discovery.ownerId,datasetId:discovery.datasetId,policyEpoch:discovery.policyEpoch,readCollection:read.href,writeCollection:write?.href??null,readTitle:read.title,writeTitle:write?.title??null,refreshPolicy:request.refreshPolicy,validFrom:source.coverageFrom,mirror:{token:null,objects:[]},pendingDeleted:[],lastCheckedAt:null,lastChangedAt:null,lastBodySha256:null,semanticSha256:null,lastError:null,nextDueAt:request.refreshPolicy==='manual'?null:new Date().toISOString(),status:'unconfirmed',awaitingApproval:false,failures:0,qaFixture:new URL(discovery.url).protocol==='http:'};value.caldav.push(record);const saved=structuredClone(value);for(const row of saved.caldav)delete row.pendingCandidate;try{await store.save(saved)}catch(error){value.caldav=value.caldav.filter(row=>row!==record);throw error}discoveries.delete(request.discoveryId);removers.set(record.id,scheduler.addJob(record.id,{sweep:()=>sweep(record),due:now=>record.refreshPolicy!=='manual'&&record.nextDueAt&&Date.parse(record.nextDueAt)<=now,run:()=>sync(record.id)}));return status(record)
    }
    const record=await account(request.id)
    if(action==='sync')return sync(record.id)
    if(action==='candidate'){if(!record.pendingCandidate)await sync(record.id);return record.pendingCandidate??null}
    if(action==='acknowledge'){if(record.lastBodySha256!==request.bodySha256)throw new Error('CALDAV_CANDIDATE_CHANGED');record.status='current';record.awaitingApproval=false;record.pendingDeleted=[];delete record.pendingCandidate;const saved=structuredClone(value);for(const row of saved.caldav)delete row.pendingCandidate;await store.save(saved);send('michi:schedule-refresh-status',status(record));return true}
    if(action==='prepare-write'){
      if(!record.writeCollection)throw new Error('CALDAV_WRITE_COLLECTION_BLOCKED');if(!['put','delete'].includes(request.operation)||typeof request.eventId!=='string'||!/^[a-f0-9-]{36}$/.test(request.eventId))throw new Error('CALDAV_WRITE_INVALID')
      const row=await readDatabase(win,'calendarEvents',request.eventId);if(!row||row.ownerId!==current.settings.profileId)throw new Error('CALDAV_EVENT_OWNER_REQUIRED')
      const stamp=new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d+Z$/,'Z'),time=at=>{if(typeof at!=='string'||new Date(at).toISOString()!==at)throw new Error('CALDAV_EVENT_TIME_INVALID');return at.replace(/[-:]/g,'').replace(/\.\d+Z$/,'Z')},escapeText=text=>String(text).replaceAll('\\','\\\\').replaceAll('\n','\\n').replaceAll(',','\\,').replaceAll(';','\\;')
      const data=request.operation==='put'?`BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//michi//JP\r\nBEGIN:VEVENT\r\nUID:michi-${row.id}@local\r\nDTSTAMP:${stamp}\r\nSEQUENCE:${row.revision??1}\r\nDTSTART:${time(row.startAt)}\r\nDTEND:${time(row.endAt)}\r\nSUMMARY:${escapeText(row.title)}\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n`:null,preview=await client(record).prepareWrite({id:row.id,operation:request.operation,data});writeBindings.set(preview.token,{eventId:row.id,revision:row.revision??1,ownerId:current.settings.profileId,datasetId:current.settings.datasetId,eventSha256:sha(JSON.stringify({title:row.title,startAt:row.startAt,endAt:row.endAt}))});return {...preview,afterSummary:{title:row.title,startAt:row.startAt,endAt:row.endAt}}
    }
    if(action==='apply-write'){
      const binding=writeBindings.get(request.token);if(!binding)throw new Error('CALDAV_WRITE_PREVIEW_EXPIRED');const check=async()=>{await context(record);const row=await readDatabase(win,'calendarEvents',binding.eventId);if(!row||row.ownerId!==binding.ownerId||binding.datasetId!==current.settings.datasetId||(row.revision??1)!==binding.revision||sha(JSON.stringify({title:row.title,startAt:row.startAt,endAt:row.endAt}))!==binding.eventSha256)throw new Error('CALDAV_EVENT_CHANGED')}
      await check();return client(record).applyWrite(request.token,async preview=>{const consent=await dialog.showMessageBox(win,{type:'question',title:'CalDAV専用カレンダーへの反映',message:preview.operation==='delete'?'専用カレンダーの予定を削除します':'専用カレンダーへ予定を反映します',detail:`対象：${record.writeTitle}\n元の値：\n${(preview.before??'新規').slice(0,1500)}\n確認した値：\n${(preview.after??'削除').slice(0,1500)}\n取得後に外部の予定が変わっていれば反映を止め、差分を作り直します。`,buttons:['この差分を反映','取消'],defaultId:1,cancelId:1,noLink:true});await check();writeBindings.delete(request.token);return consent.response===0})
    }
    if(action==='disconnect'){const consent=await dialog.showMessageBox(win,{type:'question',title:'CalDAVの取得を停止',message:'この接続の取得・書込を停止します。端末内の予定は保持します。',buttons:['接続を停止','取消'],defaultId:1,cancelId:1,noLink:true});if(consent.response!==0)return false;record.revoked=true;value.caldav=value.caldav.filter(row=>row!==record);removers.get(record.id)?.();removers.delete(record.id);clients.delete(record.id);const saved=structuredClone(value);for(const row of saved.caldav)delete row.pendingCandidate;await store.save(saved);return true}
    throw new Error('CALDAV_REQUEST_INVALID')
  })
  win.on('closed',()=>{for(const remove of removers.values())remove();removers.clear();clients.clear();discoveries.clear();writeBindings.clear()})
}
module.exports={installCalDAVIPC}
