const path=require('node:path')
const {onWindowClosed}=require('./on-window-closed.cjs')
const {createLocalAPIService}=require('./local-api-service.cjs'),{createLocalAPIServer}=require('./local-api-server.cjs')
function installLocalAPIIPC({ipcMain,win,app,safeStorage,assertFrame,readDatabase}){
 const proofs=new Map();let ready=null,server=null,startQueue=Promise.resolve()
 ipcMain.on('michi:localapi-native-proof',(event,proof)=>{try{assertFrame(event);if(!proof||Object.keys(proof).length!==3||!['configure','approve'].includes(proof.kind)||typeof proof.reference!=='string'||proof.reference.length>100||!/^[a-f0-9-]{36}$/.test(proof.nonce))return;for(const [id,v]of proofs)if(Date.now()-v.at>5000)proofs.delete(id);if(proofs.size<100)proofs.set(proof.nonce,{...proof,at:Date.now()})}catch{/* foreign proof ignored */}})
 async function service(){ready??=createLocalAPIService({directory:path.join(app.getPath('userData'),'local-api-private'),safeStorage,getContext:async()=>({settings:await readDatabase(win,'settings','main'),datasetState:await readDatabase(win,'datasetState','main')}),readDatabase:(table,key)=>readDatabase(win,table,key),verifyNativeProof:(kind,reference,nonce)=>{const p=proofs.get(nonce);proofs.delete(nonce);return Boolean(p&&p.kind===kind&&p.reference===reference&&Date.now()-p.at<=5000)}}).catch(e=>{ready=null;throw e});return ready}
 function changeServer(enable,port){const work=startQueue.then(async()=>{if(server){await server.close();server=null}if(enable){const s=await service();server=await createLocalAPIServer({service:s,port});try{await s.recordPort(server.port)}catch(e){await server.close();server=null;throw e}}});startQueue=work.catch(()=>{});return work}
 ipcMain.handle('michi:localapi',async(event,value)=>{assertFrame(event);if(!value||typeof value!=='object'||Array.isArray(value)||typeof value.action!=='string')throw new Error('LOCAL_API_REQUEST_INVALID');const action=value.action,keys=['status','pending','invalidate'].includes(action)?['action']:['configure','issue','authorize'].includes(action)?['action','input','proofNonce']:['action','input'];if(Object.keys(value).length!==keys.length||keys.some(k=>!Object.hasOwn(value,k)))throw new Error('LOCAL_API_REQUEST_INVALID');const s=await service();if(action==='status')return {...await s.status(),running:Boolean(server),url:server?'http://127.0.0.1:'+server.port+'/api/v1':null};if(action==='configure'){const result=await s.configure(value.input,value.proofNonce);await changeServer(result.enabled,result.port);return {...await s.status(),running:Boolean(server),url:server?'http://127.0.0.1:'+server.port+'/api/v1':null}}if(action==='issue')return s.issue(value.input,value.proofNonce);if(action==='pending')return s.pending();if(action==='authorize')return s.authorize(value.input,value.proofNonce);if(action==='applied')return s.applied(value.input);if(action==='reject')return s.reject(value.input);if(action==='revoke'){if(!value.input||Object.keys(value.input).length!==1||typeof value.input.tokenId!=='string')throw new Error('LOCAL_API_REQUEST_INVALID');return s.revoke(value.input.tokenId)}if(action==='invalidate'){await s.invalidate();await changeServer(false,0);return true}throw new Error('LOCAL_API_REQUEST_INVALID')})
 win.webContents.once('did-finish-load',()=>{void service().then(s=>s.status()).then(status=>{if(status.enabled)return changeServer(true,status.port)}).catch(()=>{/* Leave a failed listener stopped; status distinguishes actual running. */})})
 onWindowClosed(win,()=>{proofs.clear();void changeServer(false,0)})
}
module.exports={installLocalAPIIPC}
