const fs=require('node:fs/promises'),watch=require('node:fs').watch,path=require('node:path'),crypto=require('node:crypto')
const {scheduleURL}=require('./schedule-network.cjs')
const sha=bytes=>crypto.createHash('sha256').update(bytes).digest('hex')
const policies=['manual','daily','weekly','window_dense'],formats=['ics','csv','pdf','xlsx']
function fail(code){throw new Error(code)}
function nextDue(record,now){if(record.refreshPolicy==='manual')return null;const dense=record.refreshPolicy==='window_dense'&&Math.abs(Date.parse(record.validFrom+'T12:00:00Z')-now)<=14*86400000;return new Date(now+(record.refreshPolicy==='daily'||dense?86400000:7*86400000)).toISOString()}
function retryAfter(headers,now){const value=headers.get('retry-after');if(!value)return 0;const delay=/^\d{1,8}$/.test(value)?Number(value)*1000:Date.parse(value)-now;return Number.isFinite(delay)?Math.min(Math.max(delay,0),30*86400000):0}
function cleanStatus(record){return {id:record.id,sourceId:record.sourceId,format:record.format,kind:record.kind,displayName:record.kind==='file'?path.basename(record.filePath):new URL(record.url).origin,refreshPolicy:record.refreshPolicy,lastCheckedAt:record.lastCheckedAt,lastChangedAt:record.lastChangedAt,nextDueAt:record.nextDueAt,lastError:record.lastError,status:record.status,bodySha256:record.lastBodySha256,qaFixture:record.qaFixture===true}}
async function readSelectedFile(filePath,maximum){const before=await fs.lstat(filePath);if(!before.isFile()||before.isSymbolicLink()||before.nlink!==1||before.size>maximum||await fs.realpath(filePath)!==filePath)fail('SCHEDULE_FILE_UNSAFE');const handle=await fs.open(filePath,'r');try{const opened=await handle.stat();if(opened.ino!==before.ino||opened.dev!==before.dev||opened.size>maximum)fail('SCHEDULE_FILE_CHANGED');const bytes=await handle.readFile();const after=await fs.lstat(filePath);if(after.isSymbolicLink()||after.ino!==opened.ino||after.dev!==opened.dev||after.size!==opened.size||after.mtimeMs!==opened.mtimeMs||await fs.realpath(filePath)!==filePath)fail('SCHEDULE_FILE_CHANGED');return bytes}finally{await handle.close()}}
/** Acquisition only: it never parses calendar content or writes a task/event/fact. */
function createScheduleRefresh({store,gateway,getContext,onChanged=async()=>{},onStatus=async()=>{},notify=async()=>{},qaLoopback=false,clock=Date.now,timeoutMs=15000,pollMs=15000}) {
  let state=null,loading=null,closed=false,timer=null,ticking=false;const pending=new Map(),watchers=new Map(),dirty=new Set(),busy=new Set()
  const persist=()=>store.save(state)
  async function context(record){const current=await getContext();if(!current?.settings||current.datasetState&&current.datasetState.mode!=='active')fail('SCHEDULE_DATASET_INACTIVE');const settings=current.settings;if(record&&(record.ownerId!==settings.profileId||record.datasetId!==settings.datasetId||record.policyEpoch!==(settings.changePolicy?.epoch??0)))fail('SCHEDULE_AUTHORITY_CHANGED');if(settings.changePolicy?.stops?.routines)fail('SCHEDULE_ROUTINES_STOPPED');return settings}
  async function load(){if(!state){loading??=store.load().then(value=>{state=value;for(const record of state.subscriptions){if(record.kind==='url'){const url=scheduleURL(record.url,qaLoopback);gateway.authorizeScheduleOrigin('schedule',url.origin)}else if(record.kind==='file')observe(record)}return state});await loading}return state}
  function observe(record){if(record.refreshPolicy==='manual'||watchers.has(record.id))return;try{const watcher=watch(path.dirname(record.filePath),(_event,name)=>{if(!name||String(name)===path.basename(record.filePath))dirty.add(record.id)});watcher.on('error',()=>{watcher.close();watchers.delete(record.id)});watchers.set(record.id,watcher)}catch{/* A periodic SHA read is the fallback even when fs.watch cannot start. */}}
  async function configure(input){await load();const settings=await context();if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length!==7||!['sourceId','format','kind','url','filePath','refreshPolicy','validFrom'].every(key=>Object.hasOwn(input,key))||typeof input.sourceId!=='string'||!input.sourceId||input.sourceId.length>200||!formats.includes(input.format)||!['url','file'].includes(input.kind)||!policies.includes(input.refreshPolicy)||!/^\d{4}-\d{2}-\d{2}$/.test(input.validFrom)||Number.isNaN(Date.parse(input.validFrom+'T00:00:00Z')))fail('SCHEDULE_CONFIGURATION_INVALID');if(state.subscriptions.length>=100)fail('SCHEDULE_SUBSCRIPTION_LIMIT')
    let url=null,filePath=null
    if(input.kind==='url'){if(input.filePath!==null)fail('SCHEDULE_CONFIGURATION_INVALID');await gateway.assertAllowed('schedule');url=scheduleURL(input.url,qaLoopback).href;gateway.authorizeScheduleOrigin('schedule',new URL(url).origin)}
    else {if(input.url!==null||typeof input.filePath!=='string')fail('SCHEDULE_CONFIGURATION_INVALID');filePath=await fs.realpath(input.filePath);await readSelectedFile(filePath,input.format==='pdf'||input.format==='xlsx'?25*1024*1024:1048576)}
    const latest=await context();if(latest.profileId!==settings.profileId||latest.datasetId!==settings.datasetId||(latest.changePolicy?.epoch??0)!==(settings.changePolicy?.epoch??0))fail('SCHEDULE_AUTHORITY_CHANGED');const existing=state.subscriptions.find(row=>row.sourceId===input.sourceId&&row.ownerId===settings.profileId&&row.datasetId===settings.datasetId);if(existing)await remove(existing.id);if(url)gateway.authorizeScheduleOrigin('schedule',new URL(url).origin)
    const record={id:crypto.randomUUID(),sourceId:input.sourceId,format:input.format,kind:input.kind,url,filePath,refreshPolicy:input.refreshPolicy,validFrom:input.validFrom,ownerId:settings.profileId,datasetId:settings.datasetId,policyEpoch:settings.changePolicy?.epoch??0,etag:null,lastModified:null,lastBodySha256:null,lastCheckedAt:null,lastChangedAt:null,lastError:null,nextDueAt:input.refreshPolicy==='manual'?null:new Date(clock()).toISOString(),failures:0,status:'unconfirmed',qaFixture:url?.startsWith('http:')===true}
    state.subscriptions.push(record);await persist();if(filePath)observe(record);return cleanStatus(record)
  }
  async function fetchBody(record){const maximum=['pdf','xlsx'].includes(record.format)?25*1024*1024:1048576;if(record.kind==='file')return {bytes:await readSelectedFile(record.filePath,maximum),headers:new Headers(),notModified:false}
    const initial=scheduleURL(record.url,qaLoopback),headers=new Headers(),rehydrate=record.status==='pending'&&!pending.has(record.id);if(!rehydrate&&record.etag)headers.set('If-None-Match',record.etag);if(!rehydrate&&record.lastModified)headers.set('If-Modified-Since',record.lastModified)
    const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),timeoutMs)
    try{let target=initial
      for(let count=0;count<=3;count++){await context(record);const response=await gateway.fetch('schedule',target.href,{headers,signal:controller.signal});if([301,302,303,307,308].includes(response.status)){const location=response.headers.get('location');if(!location||count===3)fail('SCHEDULE_REDIRECT_LIMIT');const next=scheduleURL(new URL(location,target).href,qaLoopback);if(next.origin!==initial.origin)fail('SCHEDULE_CROSS_ORIGIN_REDIRECT');target=next;continue}
        if(response.status===304)return {bytes:null,headers:response.headers,notModified:true}
        if(response.status!==200){const error=new Error(`SCHEDULE_HTTP_${response.status}`);error.retryAfter=retryAfter(response.headers,clock());throw error}
        const contentType=(response.headers.get('content-type')??'').split(';')[0].trim().toLowerCase(),allowed={ics:['text/calendar','text/plain','application/octet-stream'],csv:['text/csv','text/tab-separated-values','text/plain','application/octet-stream'],pdf:['application/pdf'],xlsx:['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','application/octet-stream']}
        if(!allowed[record.format].includes(contentType))fail('SCHEDULE_CONTENT_TYPE_INVALID');const length=response.headers.get('content-length');if(length&&(!/^\d+$/.test(length)||Number(length)>maximum))fail('SCHEDULE_BODY_OVERSIZE')
        const reader=response.body?.getReader();if(!reader)fail('SCHEDULE_BODY_EMPTY');const chunks=[];let size=0;try{for(;;){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>maximum)fail('SCHEDULE_BODY_OVERSIZE');chunks.push(Buffer.from(value))}}catch(error){await reader.cancel().catch(()=>{});throw error}finally{reader.releaseLock()}
        if(!size)fail('SCHEDULE_BODY_EMPTY');return {bytes:Buffer.concat(chunks),headers:response.headers,notModified:false}
      }
    }finally{clearTimeout(timeout)}
  }
  async function refresh(id){await load();const record=state.subscriptions.find(row=>row.id===id);if(!record)fail('SCHEDULE_SUBSCRIPTION_MISSING');if(busy.has(id))return cleanStatus(record);busy.add(id)
    try{await context(record);const result=await fetchBody(record);await context(record);if(closed||!state.subscriptions.includes(record))fail('SCHEDULE_SUBSCRIPTION_REMOVED');const now=clock(),at=new Date(now).toISOString();record.lastCheckedAt=at;record.failures=0;record.lastError=null;record.nextDueAt=nextDue(record,now)
      if(result.headers.get('etag'))record.etag=result.headers.get('etag').slice(0,1000);if(result.headers.get('last-modified'))record.lastModified=result.headers.get('last-modified').slice(0,200)
      if(result.notModified){if(!record.lastBodySha256)fail('SCHEDULE_304_WITHOUT_BODY');record.status=pending.has(id)?'pending':'current';await persist();return cleanStatus(record)}
      const hash=sha(result.bytes);if(hash===record.lastBodySha256&&!(record.status==='pending'&&!pending.has(id))){record.status=pending.has(id)?'pending':'current';await persist();return cleanStatus(record)}
      record.lastBodySha256=hash;record.lastChangedAt=at;record.status='pending';const candidate={subscriptionId:id,sourceId:record.sourceId,format:record.format,fetchedAt:at,bodySha256:hash,bytes:new Uint8Array(result.bytes),qaFixture:record.qaFixture};pending.set(id,candidate);await persist();await onChanged(structuredClone(candidate));return cleanStatus(record)
    }catch(error){if(['SCHEDULE_DATASET_INACTIVE','SCHEDULE_AUTHORITY_CHANGED','SCHEDULE_ROUTINES_STOPPED','NETWORK_POLICY_OFFLINE'].includes(error.code??error.message)){record.status='paused';record.lastError='取得を設定により停止しています'}else{record.status='stale';record.lastError='取得に失敗しました。資料を確認してください';record.lastCheckedAt=new Date(clock()).toISOString();record.failures=Math.min(10,(record.failures??0)+1);record.nextDueAt=new Date(clock()+Math.max(error.retryAfter??0,Math.min(3600000,30000*2**(record.failures-1)))).toISOString()}await persist();return cleanStatus(record)
    }finally{busy.delete(id);if(!closed)await onStatus(cleanStatus(record))}
  }
  async function tick(){if(closed||ticking)return;ticking=true;try{await load();const changed=[];for(const record of [...state.subscriptions]){const due=record.nextDueAt&&Date.parse(record.nextDueAt)<=clock(),filePoll=record.kind==='file'&&record.refreshPolicy!=='manual'&&(record.status!=='stale'||due);if(!due&&!dirty.has(record.id)&&!filePoll)continue;dirty.delete(record.id);const prior=record.lastBodySha256;const result=await refresh(record.id);if(result.status==='pending'&&prior!==result.bodySha256)changed.push(result.sourceId)}if(changed.length)await notify({count:changed.length})}finally{ticking=false}}
  async function list(){await load();const settings=await getContext();return state.subscriptions.filter(row=>row.ownerId===settings?.settings?.profileId&&row.datasetId===settings?.settings?.datasetId).map(cleanStatus)}
  async function candidate(id){await load();const record=state.subscriptions.find(row=>row.id===id);await context(record);if(!record)fail('SCHEDULE_SUBSCRIPTION_MISSING');return pending.has(id)?structuredClone(pending.get(id)):null}
  async function acknowledge(id,hash){await load();const record=state.subscriptions.find(row=>row.id===id);await context(record);if(!record||!pending.has(id)||pending.get(id).bodySha256!==hash)fail('SCHEDULE_CANDIDATE_CHANGED');pending.delete(id);record.status='current';await persist();return cleanStatus(record)}
  async function remove(id){await load();const record=state.subscriptions.find(row=>row.id===id);if(!record)fail('SCHEDULE_SUBSCRIPTION_MISSING');const current=await getContext();if(record.ownerId!==current?.settings?.profileId||record.datasetId!==current?.settings?.datasetId)fail('SCHEDULE_OWNER_MISMATCH');state.subscriptions=state.subscriptions.filter(row=>row!==record);pending.delete(id);watchers.get(id)?.close();watchers.delete(id);dirty.delete(id);await persist();if(record.url&&!state.subscriptions.some(row=>row.url&&new URL(row.url).origin===new URL(record.url).origin))gateway.revokeScheduleOrigin('schedule',new URL(record.url).origin);return true}
  function start(){if(!timer){timer=setInterval(()=>void tick().catch(()=>{}),pollMs);timer.unref?.();void tick().catch(()=>{})}}
  function close(){closed=true;clearInterval(timer);timer=null;for(const watcher of watchers.values())watcher.close();watchers.clear();pending.clear()}
  return {configure,refresh,tick,list,candidate,acknowledge,remove,start,close}
}
module.exports={createScheduleRefresh,readSelectedFile,nextDue,retryAfter}
