import { useEffect, useState } from 'react'
import { useLiveQuery } from 'dexie-react-hooks'
import { db } from './db'
import { achievementDraftFor, defaultAchievementThreshold, evidenceKinds, evaluateAchievement, localAchievementPoints, type AchievementEvidenceKind } from './achievements'
import { achievementDB, checkAchievementContributionFromUI, approveAchievementFromUI, createAchievementEvidenceFromUI, editAchievementPublicEvidenceFromUI, prepareAchievementExport, publishAchievementFromUI, reconcileAchievementExport, saveAchievementDraftFromUI, saveAchievementPolicyFromUI, type AchievementProposal } from './achievements-save'
import type { GitHubAchievementsGateway, GitHubConfigurationInspection, GitHubGatewayStatus, GitHubInitializationProposal } from './github-publish-types'
import ExternalLink from './ExternalLink'
import { githubContributionLabel } from './github-contribution'
import { assertNativeEvent as native, checkGitHubStatus, localGitHubStatus, missingGitHubStatus as missing } from './achievements-status'

const stateLabels:Record<string,string>={awaiting_score:'ポイント確定待ち',awaiting_evidence:'証拠待ち',awaiting_review:'本人確認待ち',approved:'本人承認済み・未送信',committing:'送信処理中',published:'公開済み',corrected:'訂正公開済み',pr_pending:'実PRの反映待ち',unknown:'結果不明・再送停止',correction_pending:'訂正待ち',correction_approved:'訂正承認済み・未送信',failed:'公開保留・失敗',integration_not_configured:'連携未設定',awaiting_connection:'接続待ち',not_eligible:'公開対象外',ready:'接続確認済み',needs_initialization:'README初期化待ち'}
export default function AchievementsView({gateway:provided}:{gateway?:GitHubAchievementsGateway}){
  const api=provided??(window as unknown as {michiGitHubAchievements?:GitHubAchievementsGateway}).michiGitHubAchievements
  const data=useLiveQuery(async()=>({settings:await db.settings.get('main'),tasks:await db.tasks.toArray(),completions:await db.completions.toArray(),assessments:await db.assessments.toArray(),ledger:await db.ledger.toArray(),containers:await db.containers.toArray(),attachments:await db.taskAttachments.toArray(),notes:await db.taskNotes.toArray(),policies:await achievementDB.achievementPolicies.toArray(),evidence:await achievementDB.achievementEvidence.toArray(),exports:await achievementDB.achievementExports.toArray()}),[])
  const [status,setStatus]=useState<GitHubGatewayStatus>(missing),[inspection,setInspection]=useState<GitHubConfigurationInspection|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[token,setToken]=useState(''),[owner,setOwner]=useState(''),[repo,setRepo]=useState(''),[branch,setBranch]=useState('main'),[visibility,setVisibility]=useState<'public'|'private'>('public'),[connectChecked,setConnectChecked]=useState(false)
  const [threshold,setThreshold]=useState(defaultAchievementThreshold),[categoryIds,setCategoryIds]=useState<string[]>([]),[requireAttachment,setRequireAttachment]=useState(true),[completionId,setCompletionId]=useState(''),[title,setTitle]=useState(''),[body,setBody]=useState(''),[pastChecked,setPastChecked]=useState(false),[selectedEvidence,setSelectedEvidence]=useState<string[]>([]),[correctionReason,setCorrectionReason]=useState(''),[proposal,setProposal]=useState<AchievementProposal|null>(null),[publishChecked,setPublishChecked]=useState(false)
  const [kind,setKind]=useState<AchievementEvidenceKind>('artifact_file'),[attachmentId,setAttachmentId]=useState(''),[noteId,setNoteId]=useState(''),[originalText,setOriginalText]=useState(''),[publicText,setPublicText]=useState(''),[evidenceChecked,setEvidenceChecked]=useState(false),[editId,setEditId]=useState('')
  const [initialization,setInitialization]=useState<GitHubInitializationProposal|null>(null),[initializationChecked,setInitializationChecked]=useState(false)
  async function act(run:()=>Promise<unknown>){setBusy(true);setMessage('');try{await run()}catch(error){setMessage(String(error))}finally{setBusy(false)}}
  async function refresh(){setStatus(api?await api.status():missing)}
  useEffect(()=>{let active=true;void localGitHubStatus(api).then(value=>{if(active)setStatus(value)}).catch(()=>{if(active)setStatus({...missing,state:'awaiting_connection',notice:'GitHubの能力を確認できません。公開は停止しています。'})});return()=>{active=false}},[api])
  if(!data?.settings)return <section className="card"><h2>証拠付きGitHub実績</h2><p>読み込み中です。</p></section>
  const completion=data.completions.find(item=>item.id===completionId),task=data.tasks.find(item=>item.id===completion?.taskId),policy=data.policies.find(item=>item.repositoryId===status.repository?.repositoryId)??data.policies[0],evidence=data.evidence.filter(item=>item.completionId===completionId),existing=data.exports.find(item=>item.completionId===completionId&&item.repositoryId===policy?.repositoryId)
  const eligibility=completion&&task&&policy?evaluateAchievement({...data,settings:data.settings,completion,task,policy},selectedEvidence):null
  function pickCompletion(id:string){setCompletionId(id);setPastChecked(false);setCorrectionReason('');setAttachmentId('');setNoteId('');setOriginalText('');setProposal(null);setPublishChecked(false);setSelectedEvidence([]);setEditId('');setPublicText('');const draft=achievementDraftFor(data!.evidence,id);setTitle(draft?.title??'');setBody(draft?.body??'')}
  const reset=()=>{setProposal(null);setPublishChecked(false)}
  const points=localAchievementPoints(data.completions)
  return <section className="card setting-section achievements-view" aria-label="証拠付きGitHub実績"><h2>証拠付きGitHub実績</h2><p>公開は毎回、本人が内容と送信先を確認してから行います。原本のファイルや端末内のタスク名・会話は送信しません。</p><p role="status">{message||status.notice}</p>
    <GitHubQAAlert active={status.qaEmulator===true}/>
    {status.state==='needs_initialization'&&api?.prepareInitialization&&<div><p>空repositoryには、実績を含まないREADMEだけを作成します。</p><button disabled={busy} onClick={()=>void act(async()=>{setInitialization(await api.prepareInitialization!());setInitializationChecked(false)})}>README初期化案を確認</button><button disabled={busy||!api.reconcileInitialization} onClick={()=>void act(async()=>{const result=await api.reconcileInitialization!();if(result.status==='initialized')await refresh();setMessage(result.status==='initialized'?'初期化の実commitを照合しました':'初期化は結果不明です。再送せず読取照合してください')})}>初期化を読取照合（再送しない）</button></div>}
    {initialization&&<section aria-label="空repositoryの初期化案"><GitHubInitializationDetails proposal={initialization}/><label><input type="checkbox" checked={initializationChecked} onChange={event=>setInitializationChecked(event.target.checked)}/>このREADMEだけの初期化を確認した</label><button data-github-publish-configure={initialization.reference} disabled={busy||!initializationChecked||!api?.initializeEmpty} onClick={event=>void act(async()=>{native(event.nativeEvent);const result=await api!.initializeEmpty!({reference:initialization.reference,digest:initialization.digest});setInitialization(null);if(result.status==='initialized')await refresh();setMessage(result.status==='initialized'?'READMEだけを初期化しました':'初期化は結果不明です。再送せず読取照合してください')})}>確認した空repositoryを初期化</button></section>}
    <h3>端末内の実績ポイント</h3><p>GitHub標準のcontribution graphとは別の集計です。0pt、未設定、未完了を区別します。100ptの達成から100commitを作りません。</p><table><thead><tr><th>実績日</th><th>完了</th><th>確定ポイント</th><th>ポイント未設定</th></tr></thead><tbody>{points.slice(-31).map(row=><tr key={row.date}><td>{row.date}</td><td>{row.completed}件</td><td>{row.points}pt</td><td>{row.pending}件</td></tr>)}</tbody></table>
    <details><summary>実績専用のGitHub接続を設定</summary><p>本人所有の対象repositoryだけにContents書込権限（保護branchではPull requests書込権限も）を持つ専用tokenを指定します。このアプリの開発用リポジトリや既存のgh認証は使用しません。空repositoryはREADMEだけの初期化案を確認します。保護branchは専用PRを作成し、マージを読取確認します。自動投稿は行いません。</p><label>owner<input value={owner} disabled={busy||!api} onChange={event=>{setOwner(event.target.value);setInspection(null)}}/></label><label>repository名<input value={repo} disabled={busy||!api} onChange={event=>{setRepo(event.target.value);setInspection(null)}}/></label><label>default branch<input value={branch} disabled={busy||!api} onChange={event=>{setBranch(event.target.value);setInspection(null)}}/></label><label>可視性<select value={visibility} disabled={busy||!api} onChange={event=>{setVisibility(event.target.value as typeof visibility);setInspection(null)}}><option value="public">公開</option><option value="private">非公開</option></select></label><label>実績専用token<input type="password" autoComplete="off" value={token} disabled={busy||!api} onChange={event=>setToken(event.target.value)}/></label><button data-github-publish-configure="inspect" disabled={busy||!api||!token||!owner||!repo} onClick={event=>void act(async()=>{native(event.nativeEvent);const value=await api!.inspectConfiguration({token,owner:owner.trim(),name:repo.trim(),branch:branch.trim(),visibility});setToken('');setInspection(value);setConnectChecked(false)})}>対象と必要な権限を確認</button>
      {inspection&&<><p>{inspection.target.owner}/{inspection.target.name} / repository ID {inspection.target.repositoryId} / {inspection.target.visibility==='public'?'全世界に公開':'非公開'} / {inspection.target.defaultBranch} / head {inspection.target.headSha||'空repository'} / 本人所有{inspection.target.ownerVerified?'確認済み':'未確認'}</p><label><input type="checkbox" checked={connectChecked} onChange={event=>setConnectChecked(event.target.checked)}/>このrepository・可視性・書込権限を確認した</label><button data-github-publish-configure={inspection.reference} disabled={busy||!connectChecked} onClick={event=>void act(async()=>{native(event.nativeEvent);setStatus(await api!.configure({reference:inspection.reference,digest:inspection.digest}));setInspection(null)})}>このrepositoryだけを接続</button></>}
      {status.configurationId&&<button data-github-publish-configure="disconnect" disabled={busy||!api} onClick={event=>void act(async()=>{native(event.nativeEvent);setStatus(await api!.disconnect());reset()})}>実績用接続を停止</button>}
    </details>
    <p>接続状態：{stateLabels[status.state]??status.state} {status.repository&&`${status.repository.owner}/${status.repository.name} / ${status.repository.visibility} / ${status.repository.defaultBranch}`}</p>{api&&status.state!=='integration_not_configured'&&<button disabled={busy} onClick={event=>void act(async()=>setStatus(await checkGitHubStatus(api,event.nativeEvent)))}>接続状態をGitHubで確認</button>}
    <details><summary>今後の公開対象を設定</summary><label>一タスクの閾値<input type="number" min="0" max="100000" value={threshold} onChange={event=>setThreshold(Number(event.target.value))}/></label><fieldset><legend>公開対象カテゴリ（未選択は全カテゴリを確認対象）</legend>{data.containers.filter(item=>item.kind==='category'&&!item.deletedAt&&item.ownerId===data.settings!.profileId).map(item=><label key={item.id}><input type="checkbox" checked={categoryIds.includes(item.id)} onChange={event=>setCategoryIds(event.target.checked?[...categoryIds,item.id]:categoryIds.filter(id=>id!==item.id))}/>{item.name}</label>)}</fieldset><label><input type="checkbox" checked={requireAttachment} onChange={event=>setRequireAttachment(event.target.checked)}/>添付原本を必須にする（自己申告だけでは満たさない）</label><p>手動ポイントも式のポイントも本人の確定値として判定します。設定以前の完了の投稿は別に明示選択します。</p><button disabled={busy||status.state!=='ready'||!api} onClick={event=>void act(async()=>{await saveAchievementPolicyFromUI({threshold,allowedCategoryIds:categoryIds,allowedEvidenceKinds:evidenceKinds,requireAttachment,enabled:true},event.nativeEvent,api);setMessage('今後の対象設定を保存しました。自動投稿は行いません。')})}>今後の公開条件を保存</button></details>
    <h3>本人が選んだ完了実績</h3><label>完了実績<select value={completionId} onChange={event=>pickCompletion(event.target.value)}><option value="">選択してください</option>{data.completions.map(item=><option value={item.id} key={item.id}>{item.title} / {item.currentAt?'完了':'取消済み'} / {item.netPoints===null?'ポイント未設定':`${item.netPoints}pt`}</option>)}</select></label>
    {completion&&<><p>端末内のタスク名（公開しません）：{completion.title}</p><p>現在の判定：{eligibility?`${stateLabels[eligibility.state]} / ${eligibility.reason}`:`${stateLabels[status.state]} / 証拠と草稿はこの端末に保存できます`}</p><label>本人が編集した公開タイトル<input maxLength={300} value={title} onChange={event=>{setTitle(event.target.value);reset()}}/></label><label>公開する成果説明<textarea value={body} maxLength={20000} onChange={event=>{setBody(event.target.value);reset()}}/></label><button disabled={busy||!title.trim()||!body.trim()} onClick={event=>void act(async()=>{await saveAchievementDraftFromUI(completionId,title,body,event.nativeEvent);setMessage('草稿をこの端末に保存しました。GitHubへは送信していません。')})}>草稿を端末に保存</button>
      <h4>原本証拠と別の公開用説明</h4><p>添付の存在とbytes SHA-256を確認します。ウイルス検査や成果の独立検証を完了したとは表示しません。原本hashと原本文字列は公開ファイルへ含めません。</p><label>証拠種別<select value={kind} onChange={event=>{setKind(event.target.value as AchievementEvidenceKind);setAttachmentId('');setNoteId('');setEditId('')}}>{evidenceKinds.map(item=><option value={item} key={item}>{item}</option>)}</select></label><label>既存の添付原本<select value={attachmentId} disabled={Boolean(editId)} onChange={event=>{setAttachmentId(event.target.value);setNoteId('')}}><option value="">選択なし</option>{data.attachments.filter(item=>item.taskId===completion.taskId&&item.ownerId===data.settings!.profileId).map(item=><option value={item.id} key={item.id}>{item.name} / {item.size} bytes</option>)}</select></label><label>本人が書いた自己ノート<select value={noteId} disabled={Boolean(editId)} onChange={event=>{setNoteId(event.target.value);setAttachmentId('')}}><option value="">選択なし</option>{data.notes.filter(item=>item.taskId===completion.taskId&&item.ownerId===data.settings!.profileId&&item.kind==='self').map(item=><option value={item.id} key={item.id}>{item.body.slice(0,60)}</option>)}</select></label>{!attachmentId&&!noteId&&!editId&&<label>自己申告・コード等のHTTPS参照（原本、公開しません）<textarea value={originalText} onChange={event=>setOriginalText(event.target.value)}/></label>}
      <label>原本から独立して編集する公開用説明<textarea value={publicText} maxLength={20000} onChange={event=>{setPublicText(event.target.value);setEvidenceChecked(false)}}/></label><label><input type="checkbox" checked={evidenceChecked} onChange={event=>setEvidenceChecked(event.target.checked)}/>この説明に秘密や第三者の個人情報を含めず、公開対象として確認した</label><button disabled={busy||!evidenceChecked||!publicText.trim()} onClick={event=>void act(async()=>{if(editId){const row=evidence.find(item=>item.id===editId)!;await editAchievementPublicEvidenceFromUI(editId,row.revision,publicText,evidenceChecked,event.nativeEvent)}else await createAchievementEvidenceFromUI({completionId,kind,...(attachmentId?{attachmentId}:noteId?{noteId}:{originalText}),publicText,publicReviewed:evidenceChecked},event.nativeEvent);setEditId('');setPublicText('');setEvidenceChecked(false);reset();setMessage('原本と公開用説明を別に保存しました。まだ投稿していません。')})}>{editId?'公開用説明の変更を保存':'証拠と公開用説明を保存'}</button>
      <fieldset><legend>この公開へ含める説明を選択</legend>{evidence.filter(item=>item.publicText&&item.status!=='removed').map(item=><div key={item.id}><label><input type="checkbox" checked={selectedEvidence.includes(item.id)} disabled={item.status!=='ready'} onChange={event=>{setSelectedEvidence(event.target.checked?[...selectedEvidence,item.id]:selectedEvidence.filter(id=>id!==item.id));reset()}}/>{item.kind} / {item.verification} / v{item.revision} / {item.publicText}</label><button onClick={()=>{setEditId(item.id);setPublicText(item.publicText);setEvidenceChecked(false)}}>公開用説明を編集</button></div>)}</fieldset>
      <label><input type="checkbox" checked={pastChecked} onChange={event=>{setPastChecked(event.target.checked);reset()}}/>公開設定以前のこの完了実績も、本人が投稿対象として明示選択する</label>{existing?.commitSha&&<label>既存公開への訂正理由<textarea value={correctionReason} onChange={event=>{setCorrectionReason(event.target.value);reset()}}/><span>訂正理由と全ファイルを確認してから、同じrecordへ訂正commitを一度送信します。過去の草を消したとは表示しません。</span></label>}
      <button disabled={busy||!policy||status.state!=='ready'||!api||!title.trim()||!body.trim()} onClick={()=>void act(async()=>{setProposal(await prepareAchievementExport(completionId,policy!.id,{title,body,evidenceIds:selectedEvidence,includePastCompletion:pastChecked,correctionReason},api));setPublishChecked(false)})}>repository・全ファイル・証拠の公開差分を確認</button>
    </>}
    {proposal&&<section aria-label="GitHub実績の公開確認案"><h3>公開する正確な内容</h3><p>{proposal.row.manifest.repository.owner}/{proposal.row.manifest.repository.name} / ID {proposal.row.repositoryId} / {proposal.row.manifest.repository.visibility==='public'?'全世界に公開':'非公開'} / {proposal.row.manifest.repository.defaultBranch} / head {proposal.row.manifest.repository.headSha}</p><p>承認digest：{proposal.row.manifest.approvalDigest} / 期限：{proposal.row.manifest.expiresAt}</p><p>README.mdとmetricsの現在の内容を、この案の内容で置き換えます。元の添付・ノートは送信しません。</p>{proposal.row.manifest.files.map(file=><details key={file.path}><summary>{file.path} / SHA256 {file.sha256} / {new TextEncoder().encode(file.content).length} bytes</summary><pre>{file.content}</pre></details>)}<label><input type="checkbox" checked={publishChecked} onChange={event=>setPublishChecked(event.target.checked)}/>repository・可視性・branch・全path・全内容・証拠版・README置換を確認した</label><button disabled={busy||!publishChecked} onClick={event=>void act(async()=>{await approveAchievementFromUI(proposal,event.nativeEvent,api);reset();setMessage('公開案を承認してこの端末に保存しました。まだGitHubへ送信していません。')})}>確認した公開案を承認して保存</button><button disabled={busy} onClick={reset}>案を取り消す</button></section>}
    <h3>公開と照合の状態</h3>{data.exports.map(row=><section key={row.id}><p>{row.summary.title} / {stateLabels[row.state]??row.state} / {row.summary.points}pt / 公開済み値 {row.publishedSummary?.points??'なし'} / {row.failureCode==='PR_WRITE_PERMISSION_REQUIRED'?'PR作成権限がありません（Pull requests: write）':row.failureCode??''}</p><p>GitHub標準の草：{githubContributionLabel(row.contribution)}</p>{row.contributionCheck&&<p>条件の読取確認 {row.contributionCheck.checkedAt}：{row.contributionCheck.reasons.map(reason=>contributionReason(reason)).join(' / ')}</p>}{['published','corrected'].includes(row.state)&&api?.contribution&&<button disabled={busy} onClick={event=>void act(async()=>{await checkAchievementContributionFromUI(row.id,event.nativeEvent,api)})}>集計条件を読取確認（草への反映は未確認）</button>}{row.url&&<ExternalLink href={row.url}>保存済みGitHub実績を確認</ExternalLink>}{row.pullRequestUrl&&<ExternalLink href={row.pullRequestUrl}>{['published','corrected'].includes(row.state)?'マージを確認したPR':'反映待ちの実PR'}</ExternalLink>}{['approved','correction_approved'].includes(row.state)&&<button data-github-publish-approve={row.id} disabled={busy||!api||status.state!=='ready'} onClick={event=>void act(async()=>{await publishAchievementFromUI(row.id,event.nativeEvent,api);await refresh()})}>{row.previousCommitSha?'承認した訂正を一度だけ送信':'承認した内容を一度だけGitHubへ送信'}</button>}{['unknown','committing','pr_pending'].includes(row.state)&&<button disabled={busy||!api} onClick={()=>void act(async()=>{await reconcileAchievementExport(row.id,api)})}>実際のrecord・commitを読取照合（再送しない）</button>}</section>)}
  </section>
}

function contributionReason(reason:string){return ({NO_PUBLICATION_RECEIPT:'公開receiptなし',PR_NOT_MERGED:'PR未マージ',PUBLICATION_UNCONFIRMED:'公開未確認',REPOSITORY_OR_COMMIT_CHANGED:'repository・commit変更',FORK_REPOSITORY:'fork repository',DEFAULT_BRANCH_UNCONFIRMED:'既定branch未確認',NOT_ON_DEFAULT_BRANCH:'既定branchから到達しません',AUTHOR_UNCONFIRMED:'作者情報未確認',OUTSIDE_CURRENT_GRAPH_PERIOD:'過去365日の範囲外',EMAILS_UNCONFIRMED:'メール一覧未確認',AUTHOR_EMAIL_NOT_ASSOCIATED:'作者メールが本人の確認済みメールと一致しません',AUTHOR_EMAIL_PERMISSION_UNAVAILABLE:'メール確認権限なし',PRIVATE_GRAPH_SETTING_UNCONFIRMED:'非公開contributionの表示設定はAPIで確認できません',GRAPH_REFLECTION_NOT_INDEPENDENTLY_VERIFIED:'当該commitの草への独立した反映は未確認',READ_CHECK_UNAVAILABLE:'読取確認ができません'} as Record<string,string>)[reason]??'条件未確認'}

export function GitHubQAAlert({active}:{active:boolean}){return active?<p role="alert">QA用の合成GitHub（127.0.0.1）— 実GitHubではありません</p>:null}
export function GitHubInitializationDetails({proposal}:{proposal:GitHubInitializationProposal}){return <><p>{proposal.repository.owner}/{proposal.repository.name} / {proposal.repository.visibility==='public'?'全世界に公開':'非公開'} / {proposal.repository.defaultBranch} / 期限 {proposal.expiresAt} / {proposal.path} / SHA256 {proposal.sha256}</p><pre>{proposal.content}</pre></>}
