import type { EntityTable } from 'dexie'
import { db } from './db'
import { uid } from './domain'
import { canonicalJSON, contentDigest } from './canonical'
import { changePolicyFor } from './change-set'
import { assertOperationAllowed } from './automation-policy'
import { onFeatureHidden } from './features'
import { achievementCompletionDigest, achievementEvidenceOrder, achievementTextHash, buildAchievementManifest, completionScoreMode, publicAchievementText, type AchievementEvidence, type AchievementEvidenceKind, type AchievementExport, type AchievementFacts, type AchievementPolicy, type AchievementPublicSelection } from './achievements'
import { validateAchievementEvidence, validateAchievementExport, validateAchievementPolicy, verifyAchievementDigests } from './achievements-validation'
import type { GitHubAchievementsGateway, GitHubPublishResult } from './github-publish-types'

const store = db as typeof db & { achievementPolicies: EntityTable<AchievementPolicy,'id'>; achievementEvidence: EntityTable<AchievementEvidence,'id'>; achievementExports: EntityTable<AchievementExport,'id'> }
export const achievementDB = store
export async function checkAchievementContributionFromUI(exportId:string,event:Event,api=gateway()){
 human(event);if(!api.contribution)throw new Error('集計条件の確認は未接続です')
 const row=await store.achievementExports.get(exportId),owner=await settings()
 if(!row||row.ownerId!==owner.profileId||row.datasetId!==owner.datasetId||!['published','corrected'].includes(row.state))throw new Error('マージ確認済みの公開実績を選択してください')
 const check=await api.contribution({exportId})
 return db.transaction('rw',[store.achievementExports,db.settings],async()=>{const fresh=await store.achievementExports.get(exportId),current=await settings();if(!fresh||fresh.revision!==row.revision||fresh.commitSha!==row.commitSha||current.profileId!==owner.profileId||current.datasetId!==owner.datasetId)throw new Error('集計条件の確認対象が変わりました');const next={...fresh,contribution:check.status,contributionCheck:check,revision:fresh.revision+1,updatedAt:new Date().toISOString()};validateAchievementExport(next);await store.achievementExports.put(next);return next})
}
const tables = () => [db.settings,db.tasks,db.completions,db.ledger,db.assessments,db.containers,db.taskAttachments,db.taskNotes,db.audits,db.commands,store.achievementPolicies,store.achievementEvidence,store.achievementExports]
export type AchievementProposal = { row: AchievementExport; previousRevision: number | null; fingerprint: string }
const authority = new Map<string, AchievementProposal>()
export function clearAchievementAuthority() { authority.clear() }
onFeatureHidden('achievements', clearAchievementAuthority)
function human(event: Event) { const getter=Object.getOwnPropertyDescriptor(Event.prototype,'type')?.get; if(!(event instanceof Event)||!event.isTrusted||!getter||!['click','submit'].includes(getter.call(event)))throw new Error('本人確認ボタンから操作してください') }
function gateway(): GitHubAchievementsGateway { const api=(window as unknown as {michiGitHubAchievements?:GitHubAchievementsGateway}).michiGitHubAchievements; if(!api)throw new Error('integration_not_configured'); return api }
function frozen<T>(value:T):T{if(value&&typeof value==='object'){Object.freeze(value);Object.values(value).forEach(frozen)}return value}
async function settings(){const value=await db.settings.get('main');if(!value)throw new Error('本人設定がありません');return value}
async function facts(completionId:string,policyId:string):Promise<AchievementFacts>{const current=await settings(),completion=await db.completions.get(completionId),policy=await store.achievementPolicies.get(policyId);if(!completion||!policy)throw new Error('完了実績・公開設定がありません');const task=await db.tasks.get(completion.taskId);if(!task)throw new Error('タスクがありません');return {settings:current,task,completion,policy,ledger:await db.ledger.where('completionId').equals(completionId).toArray(),assessments:await db.assessments.where('taskId').equals(task.id).toArray(),containers:await db.containers.toArray(),evidence:achievementEvidenceOrder(await store.achievementEvidence.where('completionId').equals(completionId).toArray())}}
function fingerprint(value:AchievementFacts){const policy=changePolicyFor(value.settings);return canonicalJSON({...value,settings:{profileId:value.settings.profileId,datasetId:value.settings.datasetId,epoch:policy.epoch,sourcePermissionRevision:policy.sourcePermissionRevision}})}
async function verifyOrigins(value:AchievementFacts,ids:string[]){for(const item of value.evidence.filter(item=>ids.includes(item.id))){validateAchievementEvidence(item);if(item.status!=='ready'||!item.publicReviewed||await achievementTextHash(item.publicText)!==item.publicSha256)throw new Error('公開用証拠の版・確認・hashが変わりました');if(item.origin.kind==='task_attachment'){const attachment=await db.taskAttachments.get(item.origin.id!);if(!attachment||attachment.ownerId!==value.settings.profileId||attachment.taskId!==value.task.id||attachment.sha256!==item.origin.sha256||attachment.size!==item.origin.size||attachment.mediaType!==item.origin.mediaType||attachment.blob.size!==attachment.size)throw new Error('証拠の添付原本が変わりました');const hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',await attachment.blob.arrayBuffer()))].map(byte=>byte.toString(16).padStart(2,'0')).join('');if(hash!==item.origin.sha256)throw new Error('添付原本のbytes SHA-256が一致しません')}else if(item.origin.kind==='task_note'){const note=await db.taskNotes.get(item.origin.id!);if(!note||note.ownerId!==value.settings.profileId||note.taskId!==value.task.id||note.kind!=='self'||await achievementTextHash(note.body)!==item.origin.sha256)throw new Error('本人ノートの原本が変わりました')}else if(item.origin.originalText===null||await achievementTextHash(item.origin.originalText)!==item.origin.sha256)throw new Error('原本のhashが一致しません')}}
export async function saveAchievementPolicyFromUI(input: {threshold:number;allowedCategoryIds:string[];allowedEvidenceKinds:AchievementEvidenceKind[];requireAttachment:boolean;enabled:boolean},event:Event,api=gateway()):Promise<string>{
  human(event);const status=await api.status();if(status.state!=='ready'||!status.repository?.ownerVerified||!status.repository.canPush||!status.configurationId)throw new Error('integration_not_configured');return db.transaction('rw',[store.achievementPolicies,db.settings,db.audits,db.containers],async()=>{const current=await settings(),old=await store.achievementPolicies.where('repositoryId').equals(status.repository!.repositoryId).first(),at=new Date().toISOString(),row:AchievementPolicy={id:old?.id??`repository:${status.repository!.repositoryId}`,ownerId:current.profileId,datasetId:current.datasetId,repositoryId:status.repository!.repositoryId,repository:status.repository!,configurationId:status.configurationId!,authorizationRevision:status.authorizationRevision,revision:(old?.revision??0)+1,threshold:input.threshold,allowedCategoryIds:input.allowedCategoryIds,allowedEvidenceKinds:input.allowedEvidenceKinds,requireAttachment:input.requireAttachment,enabled:input.enabled,publishMode:'review_every_time',effectiveAt:at,createdAt:old?.createdAt??at,updatedAt:at};if(old&&(old.ownerId!==current.profileId||old.datasetId!==current.datasetId))throw new Error('公開設定の本人が一致しません');validateAchievementPolicy(row);const categories=await db.containers.toArray();if(row.allowedCategoryIds.some(id=>!categories.some(item=>item.id===id&&item.ownerId===current.profileId&&item.kind==='category'&&!item.deletedAt)))throw new Error('本人の公開対象カテゴリを選択してください');await store.achievementPolicies.put(row);await db.audits.add({id:uid(),taskId:null,operation:'achievement.policy',at,detail:JSON.stringify({repositoryId:row.repositoryId,revision:row.revision,threshold:row.threshold,mode:row.publishMode})});clearAchievementAuthority();return row.id})}
export async function createAchievementEvidenceFromUI(input:{completionId:string;kind:AchievementEvidenceKind;attachmentId?:string;noteId?:string;originalText?:string;publicText:string;publicReviewed:boolean},event:Event):Promise<string>{
  human(event);const current=await settings(),completion=await db.completions.get(input.completionId);if(!completion)throw new Error('完了実績がありません');const task=await db.tasks.get(completion.taskId);if(!task)throw new Error('タスクがありません');let origin:AchievementEvidence['origin'],verification:AchievementEvidence['verification']='self_reported'
  if(input.attachmentId){const attachment=await db.taskAttachments.get(input.attachmentId);if(!attachment||attachment.ownerId!==current.profileId||attachment.taskId!==task.id||attachment.blob.size!==attachment.size||input.kind==='user_statement')throw new Error('本人の添付原本を選択してください');const hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',await attachment.blob.arrayBuffer()))].map(byte=>byte.toString(16).padStart(2,'0')).join('');if(hash!==attachment.sha256)throw new Error('原本のSHA-256が一致しません');origin={kind:'task_attachment',id:attachment.id,sha256:hash,size:attachment.size,mediaType:attachment.mediaType,originalText:null};verification='attachment_present'}
  else if(input.noteId){const note=await db.taskNotes.get(input.noteId);if(!note||note.ownerId!==current.profileId||note.taskId!==task.id||note.kind!=='self')throw new Error('本人が書いた自己ノートを選んでください');origin={kind:'task_note',id:note.id,sha256:await achievementTextHash(note.body),size:new TextEncoder().encode(note.body).length,mediaType:'text/plain',originalText:note.body}}
  else {const original=input.originalText?.trim();if(!original||original.length>50000||!['user_statement','code_link','external_reference'].includes(input.kind))throw new Error('本人の原本文章・参照を指定してください');if(input.kind!=='user_statement'){const url=new URL(original);if(url.protocol!=='https:'||url.username||url.password||url.search||url.hash)throw new Error('認証情報のないHTTPS参照を指定してください')}origin={kind:input.kind==='user_statement'?'user_statement':'external_reference',id:null,sha256:await achievementTextHash(original),size:new TextEncoder().encode(original).length,mediaType:'text/plain',originalText:original}}
  const publicText=input.publicText.trim()?publicAchievementText(input.publicText):'',at=new Date().toISOString(),row:AchievementEvidence={id:uid(),ownerId:current.profileId,datasetId:current.datasetId,taskId:task.id,completionId:completion.id,revision:1,kind:input.kind,status:'ready',verification,origin,publicText,publicSha256:await achievementTextHash(publicText),publicRevision:1,publicReviewed:input.publicReviewed,createdAt:at,updatedAt:at};validateAchievementEvidence(row)
  return db.transaction('rw',tables(),async()=>{const fresh=await settings(),c=await db.completions.get(completion.id);if(fresh.profileId!==current.profileId||fresh.datasetId!==current.datasetId||canonicalJSON(c)!==canonicalJSON(completion))throw new Error('本人・完了実績が変わりました');if(origin.kind==='task_attachment'){const attachment=await db.taskAttachments.get(origin.id!);if(!attachment||attachment.sha256!==origin.sha256||attachment.size!==origin.size||attachment.mediaType!==origin.mediaType||attachment.ownerId!==current.profileId||attachment.taskId!==task.id)throw new Error('添付原本が変わりました')}if(origin.kind==='task_note'){const note=await db.taskNotes.get(origin.id!);if(!note||note.body!==origin.originalText||note.kind!=='self'||note.taskId!==task.id||note.ownerId!==current.profileId)throw new Error('本人ノートが変わりました')}await store.achievementEvidence.add(row);clearAchievementAuthority();return row.id})
}
export async function editAchievementPublicEvidenceFromUI(id:string,revision:number,text:string,reviewed:boolean,event:Event){human(event);const publicText=publicAchievementText(text),hash=await achievementTextHash(publicText);await db.transaction('rw',[store.achievementEvidence,db.settings],async()=>{const current=await settings(),row=await store.achievementEvidence.get(id);if(!row||row.ownerId!==current.profileId||row.datasetId!==current.datasetId||row.revision!==revision||row.status==='removed')throw new Error('証拠の本人・版が変わりました');await store.achievementEvidence.put({...row,publicText,publicSha256:hash,publicRevision:row.publicRevision+1,publicReviewed:reviewed,revision:row.revision+1,updatedAt:new Date().toISOString()});clearAchievementAuthority()})}
export async function saveAchievementDraftFromUI(completionId:string,title:string,body:string,event:Event){return createAchievementEvidenceFromUI({completionId,kind:'user_statement',originalText:JSON.stringify({format:'michi-achievement-local-draft',title:publicAchievementText(title,300),body:publicAchievementText(body)}),publicText:'',publicReviewed:false},event)}
export async function prepareAchievementExport(completionId:string,policyId:string,selection:AchievementPublicSelection,api=gateway()):Promise<AchievementProposal>{
  const captured=await db.transaction('r',tables(),async()=>({facts:await facts(completionId,policyId),published:await store.achievementExports.toArray()})),value=captured.facts,previous=captured.published.find(item=>item.repositoryId===value.policy.repositoryId&&item.completionId===completionId)??null
  if(previous&&['unknown','committing','preparing','pr_pending'].includes(previous.state))throw new Error('公開結果が不明です。照合が終わるまで再送しません');if(previous?.commitSha&&!selection.correctionReason.trim())throw new Error('既存の公開recordへの訂正理由を指定してください')
  await verifyOrigins(value,selection.evidenceIds);const policy=changePolicyFor(value.settings);assertOperationAllowed(policy,'achievement.publish');const status=await api.status(),at=new Date().toISOString(),clean={...structuredClone(selection),title:publicAchievementText(selection.title,300),body:publicAchievementText(selection.body),evidenceIds:selection.evidenceIds.slice().sort()}
  const publishedReceipt=previous?.publishedReceipt??(previous?.publishedSummary&&previous.commitSha?{commitSha:previous.commitSha,manifest:previous.manifest}:undefined),basis=previous&&publishedReceipt?{...previous,manifest:publishedReceipt.manifest,commitSha:publishedReceipt.commitSha}:previous
  const manifest=await buildAchievementManifest({facts:value,selection:clean,gateway:status,exportId:previous?.id??uid(),publicId:previous?.publicId??uid(),policyEpoch:policy.epoch,sourcePermissionRevision:policy.sourcePermissionRevision,previous:basis,published:captured.published,preparedAt:at,expiresAt:new Date(Date.now()+15*60000).toISOString()})
  const row:AchievementExport={...(publishedReceipt?{publishedReceipt}:{}),id:manifest.exportId,ownerId:value.settings.profileId,datasetId:value.settings.datasetId,repositoryId:value.policy.repositoryId,completionId,taskId:value.task.id,publicId:manifest.publicId,revision:(previous?.revision??0)+1,state:'awaiting_review',manifest,selection:clean,publishedSummary:previous?.publishedSummary??null,summary:{title:clean.title,body:clean.body,points:value.completion.currentAt?value.completion.netPoints!:0,scoreMode:completionScoreMode(value.completion,value.assessments,value.ledger),completionAt:value.completion.originalAt,canceled:!value.completion.currentAt},evidenceRefs:value.evidence.filter(item=>selection.evidenceIds.includes(item.id)).map(item=>({id:item.id,revision:item.revision,publicRevision:item.publicRevision,originalSha256:item.origin.sha256,publicSha256:item.publicSha256})),approvedAt:null,approvedBy:null,attemptId:null,attemptStartedAt:null,attemptCount:previous?.attemptCount??0,commitSha:previous?.commitSha??null,branch:previous?.branch??null,recordPath:`records/${manifest.recordDate.slice(0,4)}/${manifest.recordDate.slice(5,7)}/${manifest.publicId}.json`,publishedAt:previous?.publishedAt??null,url:previous?.url??null,pullRequestUrl:previous?.pullRequestUrl??null,contribution:previous?.contribution??'not_published',failureCode:null,previousCommitSha:publishedReceipt?.commitSha??previous?.commitSha??null,history:previous?.history??[],createdAt:previous?.createdAt??at,updatedAt:at};validateAchievementExport(row);const proposal=frozen({row,previousRevision:previous?.revision??null,fingerprint:fingerprint(value)});authority.set(row.id,proposal);return proposal
}
async function rowFacts(row:AchievementExport){const policy=await store.achievementPolicies.where('repositoryId').equals(row.repositoryId).first();if(!policy)throw new Error('公開設定がありません');return facts(row.completionId,policy.id)}
async function revalidate(row: AchievementExport, api: GitHubAchievementsGateway, checkGateway = true) {
  const value = await db.transaction('r', tables(), () => rowFacts(row))
  await verifyOrigins(value, row.evidenceRefs.map(item => item.id))
  await verifyAchievementDigests(value.evidence.filter(item=>row.selection.evidenceIds.includes(item.id)),[row])
  const current = changePolicyFor(value.settings)
  assertOperationAllowed(current, 'achievement.publish')
  // The native publish handler consumes its trusted-click proof before network access,
  // then checks its private connection and live repository. Avoid HTTP here between click and IPC.
  const status = checkGateway ? await api.status() : null
  const repositoryChanged = status !== null && (status.state !== 'ready' || status.configurationId !== row.manifest.configurationId || status.authorizationRevision !== row.manifest.authorizationRevision || status.repository?.repositoryId !== row.repositoryId || ['owner', 'name', 'defaultBranch', 'visibility'].some(key => status.repository![key as 'owner'|'name'|'defaultBranch'|'visibility'] !== row.manifest.repository[key as 'owner'|'name'|'defaultBranch'|'visibility']))
  if (repositoryChanged || current.epoch !== row.manifest.policyEpoch || current.sourcePermissionRevision !== row.manifest.sourcePermissionRevision || Date.parse(row.manifest.expiresAt) <= Date.now() || await achievementCompletionDigest(value) !== row.manifest.completionDigest || await contentDigest(value.policy) !== row.manifest.policyDigest || await contentDigest(value.evidence.filter(item => row.selection.evidenceIds.includes(item.id))) !== row.manifest.evidenceDigest) throw new Error('完了・証拠・公開設定・権限・期限が変わりました。差分を作り直してください')
  return value
}
export async function approveAchievementFromUI(proposal:AchievementProposal,event:Event,api=gateway()):Promise<string>{human(event);const registered=authority.get(proposal.row.id);if(!registered||canonicalJSON(proposal)!==canonicalJSON(registered))throw new Error('登録された公開案ではありません');const {approvalDigest,...unsigned}=proposal.row.manifest;if(await contentDigest(unsigned)!==approvalDigest)throw new Error('公開案が変更されました');const captured=await revalidate(proposal.row,api);if(fingerprint(captured)!==proposal.fingerprint)throw new Error('対象が変わりました');return db.transaction('rw',tables(),async()=>{if(fingerprint(await rowFacts(proposal.row))!==proposal.fingerprint)throw new Error('公開直前に対象が変わりました');const prior=await store.achievementExports.where('[repositoryId+completionId]').equals([proposal.row.repositoryId,proposal.row.completionId]).first();if((prior?.revision??null)!==proposal.previousRevision)throw new Error('同じ完了実績の公開案が保存されています');const at=new Date().toISOString(),row={...structuredClone(proposal.row),state:proposal.row.previousCommitSha?'correction_approved' as const:'approved' as const,approvedAt:at,approvedBy:proposal.row.ownerId,updatedAt:at};await store.achievementExports.put(row);await db.audits.add({id:uid(),taskId:row.taskId,operation:'achievement.approve',at,detail:JSON.stringify({exportId:row.id,repositoryId:row.repositoryId,approvalDigest,paths:row.manifest.files.map(file=>({path:file.path,sha256:file.sha256})),approvedBy:row.ownerId})});return row.id})}
async function settle(row:AchievementExport,result:GitHubPublishResult){return db.transaction('rw',[store.achievementExports,db.commands,db.settings,db.audits],async()=>{const fresh=await store.achievementExports.get(row.id),current=await settings();if(!fresh||fresh.attemptId!==row.attemptId||fresh.manifest.approvalDigest!==row.manifest.approvalDigest||fresh.ownerId!==current.profileId||fresh.datasetId!==current.datasetId)throw new Error('公開結果の対象が変わりました');const at=new Date().toISOString();if('receipt' in result){const receipt=result.receipt;const commandKey=`achievement:publish:${row.id}:${row.attemptId}`,saved=await db.commands.get(commandKey);if(saved){if(saved.hash!==row.manifest.approvalDigest||saved.resultId!==row.id||saved.at!==receipt.publishedAt||fresh.commitSha!==receipt.commitSha)throw new Error('保存済み公開receiptが一致しません');return fresh}if(receipt.exportId!==row.id||receipt.attemptId!==row.attemptId||receipt.approvalDigest!==row.manifest.approvalDigest||receipt.repositoryId!==row.repositoryId||receipt.publicId!==row.publicId||receipt.recordPath!==row.recordPath)throw new Error('公開結果のreceiptが一致しません');const next:AchievementExport={...fresh,...(result.status==='published'?{publishedReceipt:{commitSha:receipt.commitSha,manifest:fresh.manifest}}:{}),publishedSummary:result.status==='published'?fresh.summary:fresh.publishedSummary,state:result.status==='pr_pending'?'pr_pending':fresh.previousCommitSha?'corrected':'published',commitSha:receipt.commitSha,branch:receipt.branch,recordPath:receipt.recordPath,publishedAt:receipt.publishedAt,url:receipt.url,pullRequestUrl:receipt.pullRequestUrl,contribution:receipt.contribution,failureCode:null,revision:fresh.revision+1,updatedAt:at,history:[...fresh.history,{at,state:result.status,commitSha:receipt.commitSha,approvalDigest:receipt.approvalDigest}]};validateAchievementExport(next);await store.achievementExports.put(next);if(result.status==='published')await db.commands.put({key:`achievement:publish:${row.id}:${row.attemptId}`,hash:row.manifest.approvalDigest,resultId:row.id,at:receipt.publishedAt});await db.audits.add({id:uid(),taskId:row.taskId,operation:'achievement.receipt',at,detail:JSON.stringify(receipt)});return next}if(['published','corrected'].includes(fresh.state))return fresh;const status=result.status==='failed'&&fresh.state!=='unknown'||['not_published_verified','PR_CLOSED_UNMERGED'].includes(result.code)?'failed':'unknown';const next:AchievementExport={...fresh,state:fresh.previousCommitSha&&status==='failed'?'correction_pending':status as 'failed'|'unknown',failureCode:result.code.slice(0,200),revision:fresh.revision+1,updatedAt:at};await store.achievementExports.put(next);return next})}
export async function publishAchievementFromUI(exportId:string,event:Event,api=gateway()):Promise<AchievementExport>{human(event);const row=await store.achievementExports.get(exportId);if(!row||!['approved','correction_approved'].includes(row.state)||!row.approvedAt||row.approvedBy!==row.ownerId)throw new Error('本人承認済みの公開案ではありません');const captured=await revalidate(row,api,false);const reserved=await db.transaction('rw',tables(),async()=>{const current=await store.achievementExports.get(exportId);if(!current||current.revision!==row.revision||!['approved','correction_approved'].includes(current.state)||fingerprint(await rowFacts(row))!==fingerprint(captured))throw new Error('公開案が変わりました');const at=new Date().toISOString(),next:AchievementExport={...current,state:'committing',attemptId:uid(),attemptStartedAt:at,attemptCount:current.attemptCount+1,revision:current.revision+1,updatedAt:at};await store.achievementExports.put(next);return next});let result:GitHubPublishResult;try{result=await api.publish({exportId:reserved.id,attemptId:reserved.attemptId!,approvalDigest:reserved.manifest.approvalDigest})}catch{result={status:'unknown',code:'response_lost'}}try{const settled=await settle(reserved,result); if(result.status==='published')try{await api.recordReceipt({exportId:reserved.id,attemptId:reserved.attemptId!,approvalDigest:reserved.manifest.approvalDigest})}catch{/* Actual published fact remains saved. */}; return settled}catch(error){await settle(reserved,{status:'unknown',code:'invalid_or_lost_receipt'});throw error}}
export async function reconcileAchievementExport(exportId:string,api=gateway()){const row=await store.achievementExports.get(exportId);if(!row||!row.attemptId||!['unknown','committing','pr_pending'].includes(row.state))throw new Error('照合対象の公開attemptがありません');const current=await settings();if(row.ownerId!==current.profileId||row.datasetId!==current.datasetId)throw new Error('本人が一致しません');const result=await api.reconcile({exportId:row.id,attemptId:row.attemptId}),settled=await settle(row,result);if(result.status==='published')try{await api.recordReceipt({exportId:row.id,attemptId:row.attemptId,approvalDigest:row.manifest.approvalDigest})}catch{/* Actual published fact remains saved. */};return settled}
/** Original deletion/edit cancels the authority of pending exports; it never sends a correction. */
export async function reconcileAchievementExports(): Promise<void> {
  const current = await settings(), at = new Date().toISOString()
  const evidence = await store.achievementEvidence.toArray()
  for (const row of evidence.filter(item => item.status === 'ready' && item.ownerId === current.profileId && item.datasetId === current.datasetId)) {
    let valid = true
    if (row.origin.kind === 'task_attachment') {
      const original = await db.taskAttachments.get(row.origin.id!)
      valid = Boolean(original && original.ownerId === row.ownerId && original.taskId === row.taskId && original.sha256 === row.origin.sha256 && original.size === row.origin.size && original.mediaType === row.origin.mediaType)
    } else if (row.origin.kind === 'task_note') {
      const original = await db.taskNotes.get(row.origin.id!)
      valid = Boolean(original && original.ownerId === row.ownerId && original.taskId === row.taskId && original.kind === 'self' && await achievementTextHash(original.body) === row.origin.sha256)
    }
    if (!valid) await db.transaction('rw', [store.achievementEvidence, db.settings], async () => {
      const owner = await settings(), fresh = await store.achievementEvidence.get(row.id)
      if (owner.profileId !== current.profileId || owner.datasetId !== current.datasetId || !fresh || fresh.revision !== row.revision) return
      await store.achievementEvidence.put({ ...fresh, status: 'removed', publicReviewed: false, origin: { ...fresh.origin, originalText: null }, revision: fresh.revision + 1, updatedAt: at })
      clearAchievementAuthority()
    })
  }
  for (const row of await store.achievementExports.toArray()) {
    if (row.ownerId !== current.profileId || row.datasetId !== current.datasetId) continue
    let changed = false
    try {
      const value = await db.transaction('r', tables(), () => rowFacts(row))
      await verifyOrigins(value, row.evidenceRefs.map(item => item.id))
      changed = await achievementCompletionDigest(value) !== row.manifest.completionDigest || await contentDigest(value.policy) !== row.manifest.policyDigest || await contentDigest(value.evidence.filter(item => row.selection.evidenceIds.includes(item.id))) !== row.manifest.evidenceDigest
      const authority = changePolicyFor(value.settings)
      if (['approved', 'correction_approved', 'queued'].includes(row.state) && (authority.epoch !== row.manifest.policyEpoch || authority.sourcePermissionRevision !== row.manifest.sourcePermissionRevision || Date.parse(row.manifest.expiresAt) <= Date.now() || value.task.deletedAt || !row.previousCommitSha&&value.task.status !== 'completed')) changed = true
    } catch { changed = true }
    if (changed && ['approved', 'correction_approved', 'queued', 'published', 'corrected', 'pr_pending'].includes(row.state)) await db.transaction('rw', [store.achievementExports, db.settings], async () => {
      const owner = await settings(), fresh = await store.achievementExports.get(row.id)
      if (owner.profileId !== current.profileId || owner.datasetId !== current.datasetId || !fresh || fresh.revision !== row.revision) return
      await store.achievementExports.update(row.id, { state: row.commitSha ? 'correction_pending' : 'awaiting_review', approvedAt: null, approvedBy: null, revision: row.revision + 1, updatedAt: at })
      clearAchievementAuthority()
    })
  }
}
