import { useState } from 'react'
import type { Task, TimeBlock } from './domain'
import { applyDrawerMove, groupDrawerTasks, previewDrawerMove, type DrawerMove } from './drawer'

export default function BottomDrawer({ tasks, blocks, date, run }: { tasks: Task[]; blocks: TimeBlock[]; date: string; run: (fn: () => Promise<unknown>, success?: string) => Promise<boolean> }) {
  const [open, setOpen] = useState(false)
  const [selectedId, setSelectedId] = useState('')
  const [preview, setPreview] = useState<DrawerMove | null>(null)
  const groups = groupDrawerTasks(tasks, date)
  const categories = [{ label: '期限超過', items: groups.overdue }, { label: '日付なし', items: groups.unscheduled }, { label: '予定済み', items: groups.planned }]
  function stage(id: string, block: TimeBlock | null) { const task = tasks.find(item => item.id === id); if (task) setPreview(previewDrawerMove(task, date, block)) }
  const target = (label: string, block: TimeBlock | null) => <button className="drawer-drop-target" onClick={() => selectedId && stage(selectedId, block)} onDragOver={event => event.preventDefault()} onDrop={event => { event.preventDefault(); stage(event.dataTransfer.getData('application/x-michi-task-id'), block) }}>{label}</button>
  return <section className="card bottom-drawer"><button className="drawer-toggle" aria-expanded={open} onClick={() => setOpen(value => !value)}>下部タスク一覧 · {categories.reduce((sum, group) => sum + group.items.length, 0)}件 {open ? '閉じる' : '開く'}</button>{open && <><p className="muted">タスクを選ぶかドラッグして、表示日または時間枠へ移動します。変更内容を確認してから端末内に保存します。</p><div className="drawer-categories">{categories.map(group => <div key={group.label}><strong>{group.label} · {group.items.length}件</strong><div>{group.items.map(task => <button key={task.id} draggable onDragStart={event => event.dataTransfer.setData('application/x-michi-task-id', task.id)} className={selectedId === task.id ? 'selected' : ''} onClick={() => setSelectedId(task.id)}>{task.title}</button>)}</div></div>)}</div><div className="drawer-targets"><strong>移動先</strong>{target(`${date} の予定日`, null)}{blocks.filter(block => block.date === date && !block.closed).map(block => <div key={block.id}>{target(`${String(Math.floor(block.startMinute / 60)).padStart(2, '0')}:${String(block.startMinute % 60).padStart(2, '0')}〜 ${block.category}`, block)}</div>)}</div></>}{preview && <div className="modal-backdrop"><div className="card drawer-preview" role="dialog" aria-modal="true" aria-label="予定変更の確認"><h2>予定変更を確認</h2><p><strong>{preview.title}</strong></p><p>予定日: {preview.fromDate ?? '未設定'} → {preview.toDate}</p><p>時間枠: {preview.blockLabel ?? '指定なし'}</p><p>外部カレンダーへの書込: なし（未接続）。外部送信は行いません。</p><div className="export-buttons"><button className="primary-button" onClick={async () => { if (await run(() => applyDrawerMove(preview), '予定を保存しました')) { setPreview(null); setSelectedId('') } }}>端末内に保存</button><button className="secondary-button" onClick={() => setPreview(null)}>取消</button></div></div></div>}</section>
}
