import { useState } from 'react'
import { assignTaskToTimeBlock, createCalendarEvent, createTimeBlock, finishTimeBlock, linkSessionToTimeBlock, timeBlockCapacity } from './calendar-planning'
import { today, type CalendarEvent, type Container, type Task, type TimeBlock, type WorkSession } from './domain'
import { calendarItems, calendarView, type CalendarDisplay } from './calendar-view-model'

const zone = Intl.DateTimeFormat().resolvedOptions().timeZone
const minutes = (clock: string) => { const [hour, minute] = clock.split(':').map(Number); return hour * 60 + minute }
const clock = (value: number) => `${String(Math.floor(value / 60)).padStart(2, '0')}:${String(value % 60).padStart(2, '0')}`
export default function CalendarPlanningView({ blocks, events, tasks, projects, sessions, ownerId, run }: { blocks: TimeBlock[]; events: CalendarEvent[]; tasks: Task[]; projects: Container[]; sessions: WorkSession[]; ownerId: string; run: (fn: () => Promise<unknown>, success?: string) => Promise<boolean> }) {
  const [date, setDate] = useState(today()), [kind, setKind] = useState<TimeBlock['kind']>('activity'), [category, setCategory] = useState('学習'), [projectId, setProjectId] = useState(''), [start, setStart] = useState('09:00'), [end, setEnd] = useState('10:00')
  const [eventTitle, setEventTitle] = useState(''), [eventKind, setEventKind] = useState<CalendarEvent['kind']>('meeting'), [eventStart, setEventStart] = useState(`${today()}T10:00`), [eventEnd, setEventEnd] = useState(`${today()}T11:00`), [eventTaskId, setEventTaskId] = useState('')
  const [taskChoices, setTaskChoices] = useState<Record<string, string>>({}), [sessionChoices, setSessionChoices] = useState<Record<string, string>>({})
  const [display, setDisplay] = useState<CalendarDisplay>('day'), [selectedItemId, setSelectedItemId] = useState<string | null>(null)
  const ownBlocks = blocks.filter(block => block.ownerId === ownerId), ownEvents = events.filter(event => event.ownerId === ownerId)
  const dayBlocks = ownBlocks.filter(block => block.date === date).sort((a, b) => a.startMinute - b.startMinute)
  const dayEvents = ownEvents.filter(event => today(new Date(event.startAt)) === date).sort((a, b) => a.startAt.localeCompare(b.startAt))
  const load = timeBlockCapacity(date, tasks, ownBlocks)
  const allItems = calendarItems(ownEvents, ownBlocks, tasks, zone), visibleItems = calendarView(allItems, date, display), selectedItem = allItems.find(item => item.id === selectedItemId)
  const availableProjects = projects.filter(project => project.kind === 'project' && !project.deletedAt && project.ownerId === ownerId)
  return <>
    <div className="page-heading"><div><span className="eyebrow">CALENDAR</span><h1>時間枠と予定</h1><p>活動枠・案件の作業予定・会議を別々に保存します。時間が過ぎてもタスクは完了しません。</p></div></div>
    <label className="field">表示日<input aria-label="表示日" type="date" value={date} onChange={event => setDate(event.target.value)} /></label>
    <section className="card list-card"><div className="card-heading"><h2>カレンダー</h2><span className="subtle">同じ予定データを各表示で共有</span></div><div className="segmented">{([['day', '日'], ['week', '週'], ['month', '月'], ['agenda', 'Agenda'], ['timeline', 'Timeline']] as const).map(([value, label]) => <button key={value} className={display === value ? 'active' : ''} onClick={() => setDisplay(value)}>{label}</button>)}</div><div className={`calendar-items ${display}`}>{visibleItems.length ? visibleItems.map(item => <button className="calendar-item" key={item.id} onClick={() => setSelectedItemId(item.id)}><strong>{item.date} · {item.title}</strong><small>{item.allDay ? '終日' : `${item.startAt} 〜 ${item.endAt}`}</small></button>) : <p className="muted">該当する予定はありません。</p>}</div>{selectedItem && <div className="material-entry" role="status"><strong>{selectedItem.title}</strong><p>開始 {selectedItem.startAt} · 終了 {selectedItem.endAt ?? '終日'}<br />タイムゾーン {selectedItem.timezone} · 版 {selectedItem.revision}</p></div>}</section>
    <section className="card list-card"><div className="card-heading"><h2>時間枠を作成</h2></div><div className="container-create"><select aria-label="時間枠の種類" value={kind} onChange={event => { setKind(event.target.value as TimeBlock['kind']); setProjectId('') }}><option value="activity">活動枠</option><option value="work_session">案件の作業予定</option></select><input aria-label="枠のカテゴリ" value={category} maxLength={100} onChange={event => setCategory(event.target.value)} placeholder="学習など" /><input aria-label="枠の開始" type="time" value={start} onChange={event => setStart(event.target.value)} /><input aria-label="枠の終了" type="time" value={end} onChange={event => setEnd(event.target.value)} />{kind === 'work_session' && <select aria-label="作業予定の案件" value={projectId} onChange={event => setProjectId(event.target.value)}><option value="">案件を選択</option>{availableProjects.map(project => <option key={project.id} value={project.id}>{project.name}</option>)}</select>}<button className="primary-button" disabled={!date || !category.trim() || (kind === 'work_session' && !projectId)} onClick={() => run(() => createTimeBlock({ kind, category, projectId: kind === 'work_session' ? projectId : null, date, startMinute: minutes(start), endMinute: minutes(end), timezone: zone }), '時間枠を作成しました')}>作成</button></div></section>
    <section className="card list-card"><div className="card-heading"><h2>{date} の時間枠</h2><span className="subtle">容量 {load.totalMinutes}分（枠 {load.reservedMinutes}分・枠外 {load.standaloneMinutes}分）</span></div>{dayBlocks.length ? dayBlocks.map(block => <div className="container-row" key={block.id}><div className="container-main"><strong>{clock(block.startMinute)}〜{clock(block.endMinute)} {block.category}</strong><span className="status-tag">{block.kind === 'activity' ? '活動' : '作業予定'}{block.closed ? ' · 終了' : ''}</span><small>配置 {block.taskIds.length}件</small></div>{!block.closed && <><select aria-label={`${block.category}へ置くタスク`} value={taskChoices[block.id] ?? ''} onChange={event => setTaskChoices(current => ({ ...current, [block.id]: event.target.value }))}><option value="">タスクを選択</option>{tasks.filter(task => !task.deletedAt && task.status === 'open' && !block.taskIds.includes(task.id)).map(task => <option key={task.id} value={task.id}>{task.title}</option>)}</select><button className="secondary-button" disabled={!taskChoices[block.id]} onClick={() => run(() => assignTaskToTimeBlock(block.id, block.revision, taskChoices[block.id]), '時間枠へ配置しました')}>配置</button></>}{block.kind === 'work_session' && <><select aria-label={`${block.category}の実績時間`} value={sessionChoices[block.id] ?? ''} onChange={event => setSessionChoices(current => ({ ...current, [block.id]: event.target.value }))}><option value="">実績時間を選択</option>{sessions.map(session => <option key={session.id} value={session.id}>{session.minutes}分 · {tasks.find(task => task.id === session.taskId)?.title ?? 'タスク'}</option>)}</select><button className="text-button" disabled={!sessionChoices[block.id]} onClick={() => run(() => linkSessionToTimeBlock(block.id, block.revision, sessionChoices[block.id]), '実績時間をリンクしました')}>実績をリンク</button></>}<button className="text-button" disabled={block.closed} onClick={() => run(() => finishTimeBlock(block.id, block.revision), '時間枠を終了しました')}>終了</button></div>) : <p className="muted">時間枠はありません。</p>}</section>
    <section className="card list-card"><div className="card-heading"><h2>会議・授業などの予定</h2></div><div className="container-create"><select aria-label="予定の種類" value={eventKind} onChange={event => setEventKind(event.target.value as CalendarEvent['kind'])}><option value="meeting">会議</option><option value="class">授業</option><option value="other">その他</option></select><input aria-label="予定名" value={eventTitle} maxLength={300} onChange={event => setEventTitle(event.target.value)} placeholder="予定名" /><input aria-label="予定の開始" type="datetime-local" value={eventStart} onChange={event => setEventStart(event.target.value)} /><input aria-label="予定の終了" type="datetime-local" value={eventEnd} onChange={event => setEventEnd(event.target.value)} /><select aria-label="リンクする出席タスク" value={eventTaskId} onChange={event => setEventTaskId(event.target.value)}><option value="">タスクなし</option>{tasks.filter(task => !task.deletedAt).map(task => <option key={task.id} value={task.id}>{task.title}</option>)}</select><button className="primary-button" disabled={!eventTitle.trim()} onClick={async () => { if (await run(() => createCalendarEvent({ kind: eventKind, title: eventTitle, startAt: new Date(eventStart).toISOString(), endAt: new Date(eventEnd).toISOString(), timezone: zone, linkedTaskId: eventTaskId || null }), '予定を作成しました')) setEventTitle('') }}>作成</button></div>{dayEvents.length ? dayEvents.map(event => <div className="container-row" key={event.id}><strong>{event.title}</strong><span>{new Date(event.startAt).toLocaleTimeString('ja-JP', { hour: '2-digit', minute: '2-digit' })}〜{new Date(event.endAt).toLocaleTimeString('ja-JP', { hour: '2-digit', minute: '2-digit' })}</span><span className="status-tag">{event.kind === 'meeting' ? '会議' : event.kind === 'class' ? '授業' : '予定'}</span></div>) : <p className="muted">この日の予定はありません。</p>}</section>
  </>
}
