import './ScheduleSourcesPanel.css'
import { useEffect, useState } from 'react'
import { useLiveQuery } from 'dexie-react-hooks'
import { db } from './db'
import { uid, type Settings } from './domain'
import type { CalendarRulesState } from './calendar-resolver'
import { prepareCalendarICSImport } from './calendar-import'
import { applyCalendarProposalFromUI, type CalendarConfigurationProposal } from './calendar-rules-save'
import { prepareCalDAVImport, type CalDAVConnectionStatus, type CalDAVDiscovery, type CalDAVWritePreview } from './calendar-caldav'
import { acknowledgeScheduleRefresh, pendingScheduleRefreshFile } from './schedule-refresh'
import type { ScheduleRefreshInbox } from './schedule-refresh-types'
export function CalDAVImportPreview({ state, row, onApplied }: { state: CalendarRulesState; row: ScheduleRefreshInbox; onApplied: () => void|Promise<void> }) {
  const source = state.sources.find(source => source.id === row.sourceId), [from, setFrom] = useState(source?.coverageFrom ?? ''), [to, setTo] = useState(source?.coverageTo ?? ''), [floating, setFloating] = useState(false), [preview, setPreview] = useState<Awaited<ReturnType<typeof prepareCalDAVImport>> | null>(null), [checked, setChecked] = useState(false), [message, setMessage] = useState(''), [busy, setBusy] = useState(false)
  async function prepare() { setBusy(true);setPreview(null);setChecked(false);try{setPreview(await prepareCalDAVImport(row,{timezone:state.contexts.find(context=>context.id===source?.contextId)?.timezone??'Asia/Tokyo',fromDate:from,toDate:to,allowFloating:floating}))}catch(error){setMessage(String(error))}finally{setBusy(false)} }
  async function apply(event: Event){if(!preview||!checked)return;setBusy(true);try{await applyCalendarProposalFromUI(preview.proposal,event);await acknowledgeScheduleRefresh(row);await onApplied();setMessage('CalDAVの読取資料を保存しました。発生回への反映は共通カレンダーで別に確認してください。')}catch(error){setMessage(String(error))}finally{setBusy(false)} }
  return <section className="card setting-section"><h3>CalDAV読取の差分確認</h3>{row.qaFixture&&<p role="status">合成サーバーの試験資料です。</p>}<label>取込開始<input type="date" value={from} onChange={event=>{setFrom(event.target.value);setPreview(null);setChecked(false)}} /></label><label>終了<input type="date" value={to} onChange={event=>{setTo(event.target.value);setPreview(null);setChecked(false)}} /></label><label><input type="checkbox" checked={floating} onChange={event=>{setFloating(event.target.checked);setPreview(null);setChecked(false)}} />タイムゾーンのない日時へ対象のタイムゾーンを適用する</label><button disabled={busy} onClick={()=>void prepare()}>取得したCalDAVの差分を確認</button>{preview&&<><p>事実の追加 {preview.added}・更新 {preview.updated}・明示取消 {preview.canceled}</p>{preview.warnings.map(warning=><p key={warning}>{warning}</p>)}<ul>{preview.proposal.preview.map(spec=><li key={spec.generationKey}>{spec.title} · {spec.startAt}〜{spec.endAt}</li>)}</ul><label><input type="checkbox" checked={checked} onChange={event=>setChecked(event.target.checked)} />この取得資料の対象・期間・明示削除を確認しました</label><button disabled={busy||!checked} onClick={event=>void apply(event.nativeEvent)}>確認したCalDAV資料を保存</button></>}{message&&<p role="status">{message}</p>}</section>
}
export default function CalendarCalDAVView({state,settings}:{state:CalendarRulesState;settings:Settings}) {
  const [url,setURL]=useState(''),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[discovery,setDiscovery]=useState<CalDAVDiscovery|null>(null),[sourceId,setSourceId]=useState(''),[read,setRead]=useState(''),[write,setWrite]=useState(''),[dedicated,setDedicated]=useState(false),[policy,setPolicy]=useState('manual'),[contextId,setContextId]=useState(state.contexts[0]?.id??''),[title,setTitle]=useState('本人が選んだCalDAV読取元'),[seed,setSeed]=useState<CalendarConfigurationProposal|null>(null),[seedConfirmed,setSeedConfirmed]=useState(false),[connections,setConnections]=useState<CalDAVConnectionStatus[]>([]),[connectionId,setConnectionId]=useState(''),[eventId,setEventId]=useState(''),[writePreview,setWritePreview]=useState<CalDAVWritePreview|null>(null),[writeConfirmed,setWriteConfirmed]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState<ScheduleRefreshInbox|null>(null)
  const selectedContextId=contextId||state.contexts[0]?.id||''
  const events=useLiveQuery(()=>db.calendarEvents.filter(row=>row.ownerId===settings.profileId).toArray(),[settings.profileId])??[]
  const inbox=useLiveQuery(()=>db.scheduleRefreshInbox.where('state').equals('pending').filter(row=>row.ownerId===settings.profileId&&row.datasetId===settings.datasetId&&row.format==='caldav').toArray(),[settings.profileId,settings.datasetId])??[]
  useEffect(()=>{let disposed=false;const load=async()=>{try{const rows=(await window.michiCalDAV?.request({action:'list'})??[]) as CalDAVConnectionStatus[];if(!disposed)setConnections(rows)}catch{/* Acquisition errors are shown by the connection status. */}};void load();const timer=setInterval(()=>void load(),3000);return ()=>{disposed=true;clearInterval(timer)}},[settings.profileId,settings.datasetId])
  async function run(action:()=>Promise<unknown>){setBusy(true);setMessage('');try{await action();setConnections((await window.michiCalDAV?.request({action:'list'})??[]) as CalDAVConnectionStatus[])}catch(error){setMessage(String(error))}finally{setBusy(false)} }
  async function prepareSeed(){const context=state.contexts.find(context=>context.id===selectedContextId),binding=state.bindings.find(binding=>binding.contextId===selectedContextId&&binding.personId===settings.profileId&&binding.confirmed),calendar=state.calendars.find(calendar=>calendar.contextId===selectedContextId);if(!context||!binding||!calendar)throw new Error('共通カレンダーの本人対象を先に登録してください');const proposal=await prepareCalendarICSImport({contextId:selectedContextId,bindingId:binding.id,calendarId:calendar.id,feedId:`caldav-${uid()}`,title,retentionUntil:new Date(Date.now()+90*86400000).toISOString()},'BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//michi empty CalDAV source//JP\r\nEND:VCALENDAR\r\n',{fromDate:context.validFrom,toDate:context.validTo});setSeed(proposal.proposal);setSeedConfirmed(false);setSourceId(proposal.preview.sourceId)}
  return <section className="card setting-section calendar-caldav" aria-label="CalDAVの予定資料"><h2>CalDAVの予定資料</h2><p>読取対象とアプリ専用の書込先を選びます。取得した資料を保存してから、発生回の差分を別途確認してください。端末内の編集だけでは外部書込を実行しません。</p><p>読取：CalDAVの登録先。書込：別途選んだアプリ専用カレンダー。Google・OutlookのOAuth接続は未対応です。</p>
    {!window.michiCalDAV?<p>ブラウザー版はCalDAV未対応です。ICSファイルの読取を利用できます。</p>:<>
      <label>本人対象<select value={selectedContextId} disabled={busy} onChange={event=>{setContextId(event.target.value);setSeed(null);setSeedConfirmed(false)}}>{state.contexts.map(context=><option key={context.id} value={context.id}>{context.name}</option>)}</select></label><label>読取元の名前<input value={title} maxLength={300} disabled={busy} onChange={event=>{setTitle(event.target.value);setSeed(null);setSeedConfirmed(false)}} /></label><button disabled={busy} onClick={()=>void run(prepareSeed)}>空のCalDAV読取元の確認案を作る</button>
      {seed&&<><p>空の読取資料を作ります。取得・発生回の作成はまだ行いません。原本は90日保持します。</p><label><input type="checkbox" checked={seedConfirmed} onChange={event=>setSeedConfirmed(event.target.checked)} />本人対象と原本の保持期限を確認しました</label><button disabled={busy||!seedConfirmed} onClick={event=>{const native=event.nativeEvent;void run(async()=>{await applyCalendarProposalFromUI(seed,native);setSeed(null);setMessage('空の読取元を保存しました。接続先を登録してください。')})}}>確認した読取元を保存</button></>}
      <label>固定の読取元<select value={sourceId} disabled={busy} onChange={event=>setSourceId(event.target.value)}><option value="">選択してください</option>{state.sources.filter(source=>source.ics&&(source.caldav||source.ics.components.length===0)).map(source=><option key={source.id} value={source.id}>{source.title}</option>)}</select></label>
      <label>CalDAV URL<input type="url" value={url} disabled={busy} onChange={event=>{setURL(event.target.value);setDiscovery(null)}} placeholder="https://…/dav/" /></label><label>ユーザー名<input autoComplete="off" value={username} maxLength={300} disabled={busy} onChange={event=>{setUsername(event.target.value);setDiscovery(null)}} /></label><label>アプリ専用パスワード<input type="password" autoComplete="new-password" value={password} maxLength={1000} disabled={busy} onChange={event=>{setPassword(event.target.value);setDiscovery(null)}} /></label><p>認証情報はWindowsの暗号化保存領域だけに置き、バックアップやログへ含めません。</p><button disabled={busy||!url||!username||!password} onClick={()=>void run(async()=>{const result=await window.michiCalDAV!.request({action:'discover',url,username,password}) as CalDAVDiscovery|null;if(result){setDiscovery(result);setRead('');setWrite('');setDedicated(false);setPassword('')}})}>接続先を確認して一覧を取得</button>
      {discovery&&<>{discovery.qaFixture&&<p role="status">合成サーバー（127.0.0.1）の試験です。実サービスとの接続確認は未実施です。</p>}<label>読取カレンダー<select value={read} onChange={event=>{setRead(event.target.value);setWrite('');setDedicated(false)}}><option value="">選択してください</option>{discovery.collections.map(collection=><option key={collection.href} value={collection.href}>{collection.title}</option>)}</select></label><label>アプリ専用の書込カレンダー<select value={write} onChange={event=>{setWrite(event.target.value);setDedicated(false)}}><option value="">書込しない</option>{discovery.collections.filter(collection=>collection.href!==read).map(collection=><option key={collection.href} value={collection.href}>{collection.title}</option>)}</select></label>{write&&<label><input type="checkbox" checked={dedicated} onChange={event=>setDedicated(event.target.checked)} />この書込先はmichi専用で、読取対象とは別のカレンダーです</label>}<label>取得間隔<select value={policy} onChange={event=>setPolicy(event.target.value)}><option value="manual">手動</option><option value="daily">毎日</option><option value="weekly">毎週</option><option value="window_dense">有効開始前後14日は毎日・ほかは毎週</option></select></label><button disabled={busy||!read||!sourceId||Boolean(write&&!dedicated)} onClick={()=>void run(async()=>{const result=await window.michiCalDAV!.request({action:'configure',discoveryId:discovery.id,sourceId,readCollection:read,writeCollection:write||null,dedicatedConfirmed:dedicated,refreshPolicy:policy});if(result){setDiscovery(null);setMessage('CalDAVの対象を登録しました。予定は変更していません。')}})}>対象を確認して登録</button></>}
      {connections.some(connection=>connection.qaFixture)&&<p role="status">合成サーバー（127.0.0.1）の試験です。実サービスとの接続確認は未実施です。</p>}<button disabled={busy} onClick={()=>void run(async()=>{})}>保存済みの接続を表示</button><ul>{connections.map(connection=><li key={connection.id}>{connection.readTitle} · {{unconfirmed:'未確認',current:'取得済み',pending:'差分確認待ち',stale:'古い可能性',paused:'取得停止'}[connection.status]} · 最終確認 {connection.lastCheckedAt??'未確認'} · 書込 {connection.writeTitle??'未登録'}<button disabled={busy} onClick={()=>void run(()=>window.michiCalDAV!.request({action:'sync',id:connection.id}))}>CalDAVを今取得</button><button disabled={busy} onClick={()=>void run(()=>window.michiCalDAV!.request({action:'disconnect',id:connection.id}))}>CalDAV接続を停止</button></li>)}</ul>
      <h3>専用カレンダーへ反映</h3><label>アプリ専用の書込先<select value={connectionId} onChange={event=>{setConnectionId(event.target.value);setWritePreview(null);setWriteConfirmed(false)}}><option value="">選択してください</option>{connections.filter(connection=>connection.writeEnabled).map(connection=><option key={connection.id} value={connection.id}>{connection.writeTitle}</option>)}</select></label><label>端末内の予定<select value={eventId} onChange={event=>{setEventId(event.target.value);setWritePreview(null);setWriteConfirmed(false)}}><option value="">選択してください</option>{events.map(event=><option key={event.id} value={event.id}>{event.title}</option>)}</select></label>
      {(['put','delete'] as const).map(operation=><button key={operation} disabled={busy||!connectionId||!eventId} onClick={()=>void run(async()=>{setWritePreview(await window.michiCalDAV!.request({action:'prepare-write',id:connectionId,eventId,operation}) as CalDAVWritePreview);setWriteConfirmed(false)})}>{operation==='put'?'専用カレンダーへの書込差分を確認':'専用カレンダーからの削除差分を確認'}</button>)}
      {writePreview&&<><details open><summary>外部書込の差分（端末内の予定と読取カレンダーは保持します）</summary><h4>元の値</h4><pre>{writePreview.before??'新規の予定'}</pre><h4>確認した値</h4><pre>{writePreview.after??'外部の予定を削除'}</pre></details><label><input type="checkbox" checked={writeConfirmed} onChange={event=>setWriteConfirmed(event.target.checked)} />専用の書込先と今回の差分を確認しました</label><button disabled={busy||!writeConfirmed} onClick={()=>void run(async()=>{const result=await window.michiCalDAV!.request({action:'apply-write',id:connectionId,token:writePreview.token}) as {state:string;current?:string|null};setWritePreview(null);setWriteConfirmed(false);setMessage(result.state==='conflict'?`外部の予定が変わったため反映を止めました。差分を作り直して承認してください。\n現在の値：${result.current??'予定なし'}`:`専用カレンダーへの結果：${({written:'反映しました',deleted:'削除しました',unchanged:'同じ内容を確認しました',reconciled:'同じ内容の反映を照合しました',already_absent:'既に予定がないことを確認しました',canceled:'取り消しました'} as Record<string,string>)[result.state]??'結果の確認が必要です'}`)})}>今回の外部書込を確認して実行</button></>}
    </>}
    <h3>CalDAV資料の確認待ち</h3>{inbox.map(row=><button key={row.id} disabled={busy} onClick={()=>void run(async()=>{await pendingScheduleRefreshFile(row);setSelected(row)})}>{row.fetchedAt} · CalDAVの差分を開く</button>)}{selected&&<CalDAVImportPreview key={selected.id} state={state} row={selected} onApplied={()=>setSelected(null)} />}{message&&<p role="status">{message}</p>}
  </section>
}
