import 'fake-indexeddb/auto'
import {beforeEach,it,expect} from 'vitest'
import {readFileSync} from 'node:fs'
import {createRequire} from 'node:module'
import {db,ensureSettings} from './db'
import {completeTask} from './commands'
import {calendarFixture,monthlyRule} from './calendar-test-fixtures'
import {prepareCalendarCSVImport,verifyCSVOriginalDigests} from './calendar-csv-import'
import {applyCalendarCSVImportFromUI,clearCalendarCSVImportAuthority} from './calendar-csv-import-save'
import {applyCalendarProposalFromUI,prepareCalendarConfiguration,prepareCalendarGeneration,prepareCalendarScheduleImport,clearCalendarRulesAuthority,loadCalendarRulesState} from './calendar-rules-save'
import {tableCSVBytes,tableEvidence,type ScheduleDocumentExtraction} from './calendar-document-import'
import type {CSVMappingProfile} from './calendar-csv-mapping'
const extractScheduleDocument=createRequire(import.meta.url)('../electron/document-extract.cjs').extractScheduleDocument as (input:{name:string;bytes:Uint8Array;yTolerance:number;xGap:number})=>Promise<ScheduleDocumentExtraction>
const from='2026-10-01',to='2026-10-15',click=()=>{const event=new Event('click');Object.defineProperty(event,'isTrusted',{value:true});return event}
beforeEach(async()=>{clearCalendarRulesAuthority();clearCalendarCSVImportAuthority();await db.delete();await db.open();await ensureSettings()})
it('AT-M06: JSON class substitution and workday move, PDF company holiday, SJIS published shift share the same resolver and keep completed points',async()=>{
 const settings=(await db.settings.get('main'))!,state=calendarFixture(),period={validFrom:'2026-01-01',validTo:'2026-12-31',revision:1}
 state.ownerId=settings.profileId;state.datasetId=settings.datasetId;state.bindings[0].personId=settings.profileId;state.activities[0].weekdays=[1];state.bindings[0].activityIds.push('night');state.activities.push({...state.activities[0],id:'night',title:'本人公開夜勤',weekdays:[]})
 state.contexts.push({id:'school',name:'本人授業',domain:'education',timezone:'Asia/Tokyo',...period});state.bindings.push({id:'student',contextId:'school',personId:settings.profileId,personRef:null,activityIds:['class'],weekdays:[1],confirmed:true,...period});state.calendars.push({id:'school-days',contextId:'school',name:'授業日',weekdays:[1],...period});state.activities.push({id:'class',contextId:'school',bindingId:'student',calendarId:'school-days',title:'月曜授業',eventKind:'class',weekdays:[1],startTime:'09:00',endTime:'10:00',endDayOffset:0,...period})
 state.rules=[monthlyRule({trigger:{kind:'activity_relative',activityId:'work',edge:'start',offsetDays:0,offsetMinutes:0}})]
 const {contexts,bindings,calendars,activities,sources,facts,rules}=state;await applyCalendarProposalFromUI(await prepareCalendarConfiguration({contexts,bindings,calendars,activities,sources,facts,rules},1,from,to),click());await applyCalendarProposalFromUI(await prepareCalendarGeneration(from,to),click())
 const task=(await db.tasks.toArray()).find(row=>row.scheduledDate==='2026-10-05')!;await completeTask(task.id,task.revision);const completed=await db.tasks.get(task.id),ledger=await db.ledger.toArray(),completions=await db.completions.toArray();const work12=(await db.calendarEvents.toArray()).find(row=>row.title==='出勤'&&row.startAt.startsWith('2026-10-12'))!
 for(const [contextId,source,fact] of [['school',{id:'school-official',title:'正式授業振替',authorityScope:'calendar'},{id:'class-thursday',kind:'substitute_pattern',calendarId:'school-days',date:'2026-10-08',patternWeekday:1,mode:'replace'}],['company',{id:'activity',title:'正式勤務日変更',authorityScope:'activity'},{id:'work-move',kind:'reschedule',activityId:'work',originalDate:'2026-10-12',newDate:'2026-10-13'}]] as const){await applyCalendarProposalFromUI(await prepareCalendarScheduleImport(contextId,{format:'coach-schedule-facts',version:1,source:{...source,coverageFrom:'2026-01-01',coverageTo:'2026-12-31',revision:2},facts:[{...fact,revision:1,validity:'active',supersedes:[]}]},from,to),click())}
 const headers=['勤務ID','版','氏名','公開','状態','勤務日','開始','終了'],fields=['shift_id','record_revision','person_ref','published','status','start_date','start_time','end_time'],roster:CSVMappingProfile={version:1,name:'本人SJIS確認',revision:1,kind:'roster',encoding:'shift_jis',delimiter:',',headerRow:1,dataStartRow:2,columns:Object.fromEntries(fields.map((field,index)=>[field,{index,headerText:headers[index]}])),dateFormat:'YYYY/M/D',explicitYear:null,timeFormat:'HH:MM',endDayRule:'next_day_when_end<=start',statusMap:{勤務:'scheduled',取消:'cancelled'},publishedMap:{公表:true,下書き:false},recordIdStrategy:'column',revisionStrategy:'column'}
 const shift=await prepareCalendarCSVImport({kind:'roster',contextId:'company',bindingId:'self',calendarId:'business',activityId:'night',feedId:'sjis-night',title:'公表済み本人勤務表',retentionUntil:'2027-01-01T00:00:00.000Z'},new Uint8Array(readFileSync(new URL('../docs/examples/roster-sjis-mapped.csv',import.meta.url))),{fromDate:from,toDate:to,mappingProfile:roster});expect(shift.preview).toMatchObject({selectedCount:1,excludedOtherPerson:1,excludedDraft:1});await applyCalendarCSVImportFromUI(shift,shift.digest,click())
 const extraction=await extractScheduleDocument({name:'calendar.pdf',bytes:new Uint8Array(readFileSync(new URL('../docs/examples/calendar-pdf-table.pdf',import.meta.url))),yTolerance:2,xGap:12}),table=extraction.tables[0],calendar:CSVMappingProfile={...roster,name:'正式休日PDFの列',kind:'calendar',encoding:'utf-8',columns:Object.fromEntries(['record_id','record_revision','date','status'].map((field,index)=>[field,{index,headerText:table.rows[0].cells[index]}])),dateFormat:'YYYY-MM-DD',statusMap:{closed:'closed',open:'open',withdrawn:'withdrawn'},publishedMap:{}}
 const holiday=await prepareCalendarCSVImport({kind:'calendar',contextId:'company',bindingId:'self',calendarId:'business',activityId:null,feedId:'pdf-holidays',title:'正式会社休日PDF',retentionUntil:'2027-01-01T00:00:00.000Z'},tableCSVBytes(table),{fromDate:from,toDate:to,mappingProfile:calendar,documentEvidence:tableEvidence(extraction,table)});await applyCalendarCSVImportFromUI(holiday,holiday.digest,click());await verifyCSVOriginalDigests([await loadCalendarRulesState()])
 const proposal=await prepareCalendarGeneration(from,to);expect(proposal.plan.conflicts).toEqual([]);expect(proposal.plan.cancels.some(row=>row.before.entityId===task.id)).toBe(false);expect(proposal.plan.creates.some(row=>row.title==='月曜授業'&&row.startAt?.startsWith('2026-10-08'))).toBe(true);expect(proposal.plan.creates.filter(row=>row.title==='本人公開夜勤')).toHaveLength(1);expect(proposal.plan.updates.some(row=>row.before.entityId===work12.id&&row.after.startAt?.startsWith('2026-10-13'))).toBe(true);expect(proposal.plan.cancels.some(row=>row.before.spec.title==='出勤'&&row.before.spec.startAt?.startsWith('2026-10-05'))).toBe(true)
 await applyCalendarProposalFromUI(proposal,click());expect(await db.tasks.get(task.id)).toEqual(completed);expect(await db.ledger.toArray()).toEqual(ledger);expect(await db.completions.toArray()).toEqual(completions);expect((await db.calendarEvents.get(work12.id))?.startAt).toBe('2026-10-13T00:00:00.000Z');expect((await prepareCalendarGeneration(from,to)).plan).toMatchObject({creates:[],updates:[],cancels:[]})
 // An official closure contradicts the already published night shift; only the affected series is held in the plan.
 await applyCalendarProposalFromUI(await prepareCalendarScheduleImport('company',{format:'coach-schedule-facts',version:1,source:{id:'calendar',title:'正式休業',authorityScope:'calendar',coverageFrom:'2026-01-01',coverageTo:'2026-12-31',revision:2},facts:[{id:'closed-night',revision:1,kind:'closed',calendarId:'business',date:'2026-10-03',validity:'active',supersedes:[]}]},from,to),click());const conflict=await prepareCalendarGeneration(from,to);expect(conflict.plan.conflicts.length).toBeGreaterThan(0);expect(conflict.plan.cancels.some(row=>row.before.spec.title==='本人公開夜勤')).toBe(false);expect(await db.ledger.toArray()).toEqual(ledger)
})
