import { useEffect, useState } from 'react'
import { today, type Settings } from './domain'
import { confirmImportedSpeakerFromUI, confirmedImportedSpeakers, importSelectedExternalMessagesFromUI, prepareExternalMessageImport, type ExternalImportProvider, type ExternalImportResult, type PreparedExternalMessageImport } from './external-message-import'

const initialFrom = () => { const date = new Date(`${today()}T12:00:00Z`); date.setUTCDate(date.getUTCDate() - 29); return date.toISOString().slice(0, 10) }
const example = '[{"id":"123456789012345678","channel_id":"234567890123456789","author":{"id":"345678901234567890","username":"話者"},"content":"本人が選んだ本文","timestamp":"2026-10-01T09:00:00+09:00","edited_timestamp":null}]'
export default function ExternalMessageImportView({ settings, onImported }: { settings: Settings; onImported?: (result: ExternalImportResult) => void }) {
  const [provider, setProvider] = useState<ExternalImportProvider>('line'), [filename, setFilename] = useState('選択したLINE履歴.txt'), [raw, setRaw] = useState(''), [timezone, setTimezone] = useState(() => Intl.DateTimeFormat().resolvedOptions().timeZone)
  const [fromDate, setFromDate] = useState(initialFrom), [toDate, setToDate] = useState(today), [conversation, setConversation] = useState('')
  const [preview, setPreview] = useState<PreparedExternalMessageImport | null>(null), [selected, setSelected] = useState<string[]>([]), [confirmed, setConfirmed] = useState<string[]>([]), [notice, setNotice] = useState(''), [busy, setBusy] = useState(false)
  useEffect(() => { const reset = window.setTimeout(() => { setPreview(null); setSelected([]); setConfirmed([]); setRaw('') }, 0); return () => window.clearTimeout(reset) }, [settings.profileId, settings.datasetId])
  function invalidate() { setPreview(null); setSelected([]); setConfirmed([]); setNotice('') }
  async function parse() {
    setBusy(true); invalidate()
    try { setPreview(await prepareExternalMessageImport({ provider, filename, raw, timezone, fromDate, toDate, conversation: conversation || undefined })); setNotice('話者・日時・原文範囲を確認して、保存する発言を選択してください。') }
    catch (failure) { setNotice(failure instanceof Error ? failure.message : String(failure)) }
    finally { setBusy(false) }
  }
  return <section className="card setting-section" aria-label="選択したLINE・Discord履歴の取込">
    <h2>選択したLINE・Discord履歴の取込</h2>
    <p>本人が選んだファイル・貼付文を、この端末の手動snapshotとして保存します。全トーク・全DMの自動同期ではありません。アカウント認証・user token・self-botは使用しません。</p>
    <label className="field">形式<select disabled={busy} value={provider} onChange={event => { setProvider(event.target.value as ExternalImportProvider); setFilename(event.target.value === 'line' ? '選択したLINE履歴.txt' : '選択したDiscord発言.json'); invalidate() }}><option value="line">LINEのテキスト履歴</option><option value="discord">Discordの選択メッセージJSON配列</option></select></label>
    <label className="field">本人が選択したUTF-8ファイル<input type="file" accept={provider === 'line' ? '.txt,text/plain' : '.json,application/json'} disabled={busy} onChange={event => { const file = event.target.files?.[0]; if (!file) return; invalidate(); setBusy(true); void (async () => { if (file.size > 2 * 1024 * 1024) throw new Error('2MiB以下のファイルを選んでください'); const text = new TextDecoder('utf-8', { fatal: true, ignoreBOM: true }).decode(await file.arrayBuffer()); if (text.length > 200000) throw new Error('200000文字を超える履歴は分けてください'); setFilename(file.name.slice(0, 200)); setRaw(text) })().catch(failure => setNotice(failure instanceof Error ? failure.message : String(failure))).finally(() => setBusy(false)) }} /></label>
    <label className="field">原本名<input disabled={busy} value={filename} maxLength={200} onChange={event => { setFilename(event.target.value); invalidate() }} /></label>
    <label className="field">選択した原文・貼付文<textarea aria-label="選択履歴の原文" disabled={busy} rows={7} maxLength={200000} value={raw} onChange={event => { setRaw(event.target.value); invalidate() }} /></label>
    <div className="form-grid"><label className="field">選択した会話名（空欄は見出しから）<input disabled={busy} value={conversation} maxLength={100} onChange={event => { setConversation(event.target.value); invalidate() }} /></label><label className="field">日時を確認するタイムゾーン<input aria-label="履歴のタイムゾーン" disabled={busy} value={timezone} onChange={event => { setTimezone(event.target.value); invalidate() }} placeholder="Asia/Tokyo" /></label><label className="field">取込開始日<input type="date" disabled={busy} value={fromDate} onChange={event => { setFromDate(event.target.value); invalidate() }} /></label><label className="field">取込終了日<input type="date" disabled={busy} value={toDate} onChange={event => { setToDate(event.target.value); invalidate() }} /></label></div>
    <p className="muted">LINEは見出し・日付行・「時刻 TAB 話者 TAB 本文」の形式を解析します。日付は選択timezoneで確認してください。Discordは文字列のid・channel_id・author・content・timestampを持つJSON配列に対応します。添付・URLを自動取得しません。ZIP・HTML・別exporterの独自形式は未対応です。</p>
    {provider === 'discord' && <details><summary>対応する選択JSONの例</summary><pre style={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere' }}>{example}</pre></details>}
    <button className="secondary-button" disabled={busy || !raw.trim()} onClick={parse}>{busy ? '処理しています…' : '保存前のプレビューを作る'}</button>
    {preview && <>
      <h3>手動snapshotの保存範囲</h3><p>{preview.conversation} · {preview.fromDate}〜{preview.toDate} · {preview.timezone}</p><p>解析{preview.originalMessageCount}件、期間内{preview.messages.length}件、期間外{preview.excludedCount}件。欠落・過去編集・削除履歴・全履歴の完全性は確認していません。</p><small style={{ overflowWrap: 'anywhere' }}>原本 SHA-256: {preview.fileSha256}。選択範囲の原文片だけ保存し、ファイル全体は保存しません。</small>
      <h3>本人として確認する話者（初期値は全員未確認）</h3>
      <p className="muted">表示名がプロフィール名と同じでも本人とは断定しません。LINEは表示名しかないため、同じ表示名に別人が混在する場合は本人確認をせず資料を分けてください。</p>
      {preview.speakers.map(speaker => <div key={speaker.key} className="setting-line"><div><strong>{speaker.label}</strong><small style={{ overflowWrap: 'anywhere' }}>{speaker.idBased ? '文字列の外部話者ID' : 'この原本内の表示名'}: {speaker.key}</small></div><button className="secondary-button" disabled={busy || confirmed.includes(speaker.key) || preview.messages.some(message => message.actorKey === speaker.key && message.kind !== 'message')} onClick={async event => { try { await confirmImportedSpeakerFromUI(preview, speaker.key, event.nativeEvent); setConfirmed(confirmedImportedSpeakers(preview)); setNotice('選んだ原本の話者を本人として明示確認しました。') } catch (failure) { setNotice(failure instanceof Error ? failure.message : String(failure)) } }}>{confirmed.includes(speaker.key) ? '本人が明示確認済み' : 'この原本の話者は私本人です'}</button></div>)}
      <p>保存する発言 {selected.length} / 200件</p><div className="export-buttons"><button className="text-button" disabled={busy || preview.messages.length > 200} onClick={() => setSelected(preview.messages.map(message => message.id))}>期間内の発言をすべて選ぶ</button><button className="text-button" disabled={busy} onClick={() => setSelected([])}>選択を解除</button></div>
      {preview.messages.map(message => <article key={message.id} className="card" style={{ marginTop: 10 }}><label><input type="checkbox" disabled={busy || !selected.includes(message.id) && selected.length >= 200} checked={selected.includes(message.id)} onChange={event => setSelected(ids => event.target.checked ? [...ids, message.id] : ids.filter(id => id !== message.id))} /> {message.localDate} {message.localTime} · {message.authorLabel ?? '話者情報なし'} · {message.actorKey && confirmed.includes(message.actorKey) ? '本人が明示確認済み' : '話者未確認'} · {message.kind === 'system' ? 'Bot/system等の発言' : message.kind === 'attachment-only' ? '添付のみ・本文なし' : '通常発言'}</label><p className="muted">正規化日時 {message.sentAt}{message.editedAt ? ` · 編集日時 ${message.editedAt}` : ''} · 原文位置 {message.rawStart}〜{message.rawEnd}（0基準）{message.lineFrom ? ` · 行${message.lineFrom}〜${message.lineTo}` : ` · JSON Pointer ${message.pointer}`}</p><blockquote style={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere' }}>{message.body}</blockquote>{message.referencedQuote && <details><summary>返信先の引用（この話者の新しい発言ではありません）</summary><p>{message.referencedQuote.authorLabel ?? '引用元話者未確認'} / {message.referencedQuote.externalMessageId}</p><blockquote>{message.referencedQuote.body}</blockquote></details>}{message.spans.some(span => span.kind !== 'body') && <p className="muted">引用・転送または引用範囲の不確実な行があります。義務検出では元の発言と混同せず確認が必要です。</p>}{message.warnings.map(warning => <small key={warning} style={{ display: 'block' }}>{warning}</small>)}<details><summary>immutable保存する原文片を確認</summary><pre style={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere' }}>{message.rawExcerpt}</pre></details></article>)}
      <button className="primary-button" disabled={busy || !selected.length} onClick={async event => { setBusy(true); try { const result = await importSelectedExternalMessagesFromUI(preview, selected, event.nativeEvent); setNotice(result.notice); setPreview(null); setSelected([]); setConfirmed([]); setRaw(''); onImported?.(result) } catch (failure) { setNotice(failure instanceof Error ? failure.message : String(failure)) } finally { setBusy(false) } }}>選んだ発言をローカル資料に保存</button>
      <p className="muted">保存はタスクを作成しません。AI送信・通知・外部変更は初期値で不許可です。必要な資料だけ後で資料画面の許可を変更し、既存の検出・人間レビューへ進めます。同じ原本・位置・日時の再取込を保護し、削除済み資料はこの操作で復活させません。</p>
    </>}
    {notice && <p role="status">{notice}</p>}
  </section>
}
