import { useEffect, useState } from 'react'
import { useLiveQuery } from 'dexie-react-hooks'
import { today, type Settings } from './domain'
import { refreshLocalRetrieval, searchLocalContext, type LocalRetrievalResult } from './local-retrieval'
import { purgeExpiredCoachContext } from './context-retention'
import { bridgeEmbedder, searchHybrid, refreshHybridRetrieval, type HybridResult } from './hybrid-retrieval'
import { db } from './db'

export default function LocalRetrievalView({ settings, onConversation, onSources }: { settings: Settings; onConversation?: (id: string) => void; onSources?: (ids: string[]) => void }) {
  const [query, setQuery] = useState(''), [from, setFrom] = useState('2020-01-01'), [to, setTo] = useState(today), [result, setResult] = useState<LocalRetrievalResult | null>(null), [error, setError] = useState(''), [busy, setBusy] = useState(false), [clock, setClock] = useState(0)
  useEffect(() => { const refresh = () => { setClock(value => value + 1); void purgeExpiredCoachContext().catch(failure => setError(failure instanceof Error ? failure.message : String(failure))) }, timer = window.setInterval(refresh, 60000); refresh(); window.addEventListener('focus', refresh); return () => { window.clearInterval(timer); window.removeEventListener('focus', refresh) } }, [settings.profileId, settings.datasetId])
  const [hybrid, setHybrid] = useState<HybridResult | null>(null), [useSemantic, setUseSemantic] = useState(false)
  const [chosen, setChosen] = useState<string[]>([])
  const sources = useLiveQuery(() => db.contextSources.where('ownerId').equals(settings.profileId).toArray(), [settings.profileId]) ?? []
  const current = useLiveQuery<LocalRetrievalResult | HybridResult | null>(() => hybrid ? refreshHybridRetrieval(hybrid) : result ? refreshLocalRetrieval(result) : null, [result, hybrid, settings.profileId, settings.datasetId, settings.changePolicy?.epoch, clock])
  return <details className="conversation-search"><summary>資料と保存した会話をまとめて検索</summary>{settings.embedding && window.michiAI?.embedTexts && <label><input type="checkbox" checked={useSemantic} onChange={event => setUseSemantic(event.target.checked)} />意味検索（端末内の埋め込みサービス）も使う</label>}{!window.michiAI?.embedTexts && <p className="muted">このブラウザーでは端末内の文字検索を使います。</p>}<label className="field">検索語<input aria-label="資料と会話の検索語" value={query} maxLength={200} onChange={event => setQuery(event.target.value)} /></label><div className="form-grid"><label className="field">開始日<input type="date" value={from} onChange={event => setFrom(event.target.value)} /></label><label className="field">終了日<input type="date" value={to} onChange={event => setTo(event.target.value)} /></label></div><button className="secondary-button" disabled={busy || !query.trim()} onClick={async () => { setBusy(true); setError(''); try { setHybrid(null); setResult(null); if (useSemantic) setHybrid(await searchHybrid(query, from, to, bridgeEmbedder(settings))); else setResult(await searchLocalContext(query, from, to)) } catch (failure) { setError(failure instanceof Error ? failure.message : String(failure)) } finally { setBusy(false) } }}>資料と会話を検索</button>
    {current && <><p className="muted">{current.notice}</p><p>取得・保存が確認できる範囲（完全な履歴ではありません）:</p>{current.coverage.map(range => <p key={`${range.kind}:${range.id}`} className="muted">{range.kind === 'library' ? '資料' : '端末内の会話'} · {range.fromDate}〜{range.toDate}</p>)}{current.hits.length === 0 && <p>指定期間の許可済み保存データに一致がありません。未取得履歴に依頼がないことは確認できません。</p>}{current.hits.map(hit => <article key={`${hit.kind}:${hit.id}`} style={{ marginTop: 14 }}>{hit.kind === "library" && onSources && <label><input type="checkbox" checked={chosen.includes(hit.documentId)} onChange={event => setChosen(ids => event.target.checked ? [...new Set([...ids, hit.documentId])].slice(0, 10) : ids.filter(id => id !== hit.documentId))} />この資料を会話で参照する</label>}<strong>{hit.kind === 'library' ? '資料' : '会話'} · {hit.title}</strong><p className="muted">{hit.provider} · {hit.author} · {hit.kind === 'library' ? '資料日' : '保存日時'} {hit.date}</p>{"matchedBy" in hit && <small>{({ lexical: "文字一致", vector: "意味的に近い", both: "文字一致・意味的に近い" } as Record<string, string>)[String(hit.matchedBy)]}</small>}<blockquote style={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere' }}>{hit.quote.slice(0, 3000)}{hit.quote.length > 3000 ? '\n（引用の先頭3000文字を表示）' : ''}</blockquote><small style={{ overflowWrap: 'anywhere' }}>{hit.location ? `${hit.location} · ` : ""}出典 {hit.documentId} / {hit.id} · 版 {hit.revision} · 文字位置 {hit.start}〜{hit.end}（0基準）</small>{hit.kind === 'conversation' && onConversation && <button className="text-button" onClick={() => onConversation(hit.documentId)}>この会話を開く</button>}</article>)}</>}{onSources && chosen.length > 0 && <button className="secondary-button" onClick={async () => { try { const fresh = hybrid ? await refreshHybridRetrieval(hybrid) : result ? await refreshLocalRetrieval(result) : null; const ids = chosen.filter(id => fresh?.hits.some(hit => hit.kind === "library" && hit.documentId === id) && sources.some(source => source.id === id && (!settings.aiEnabled || source.permissions.aiEgress && source.allowedModels.includes(settings.aiModel ?? "")))); onSources(ids); setError(ids.length < chosen.length ? "AI送信未許可・失効した資料は会話へ渡さず、端末内の引用として表示します" : "会話で参照する資料を選択しました。送信は会話の確認操作で行います"); } catch (failure) { setError(String(failure)) } }}>選んだ検索結果をコーチに渡す</button>}{error && <p role="alert">{error}</p>}
    <p className="muted">検索と引用表示だけでは外部AIへ送信しません。会話へ送る資料・記憶は別に本人が選択します。</p>
  </details>
}
