import { useEffect, useState } from 'react'
import { useLiveQuery } from 'dexie-react-hooks'
import { today, type Settings } from './domain'
import { refreshLocalRetrieval, searchLocalContext, type LocalRetrievalResult } from './local-retrieval'
import { purgeExpiredCoachContext } from './context-retention'

export default function LocalRetrievalView({ settings, onConversation }: { settings: Settings; onConversation?: (id: string) => void }) {
  const [query, setQuery] = useState(''), [from, setFrom] = useState('2020-01-01'), [to, setTo] = useState(today), [result, setResult] = useState<LocalRetrievalResult | null>(null), [error, setError] = useState(''), [busy, setBusy] = useState(false), [clock, setClock] = useState(0)
  useEffect(() => { const refresh = () => { setClock(value => value + 1); void purgeExpiredCoachContext().catch(failure => setError(failure instanceof Error ? failure.message : String(failure))) }, timer = window.setInterval(refresh, 60000); refresh(); window.addEventListener('focus', refresh); return () => { window.clearInterval(timer); window.removeEventListener('focus', refresh) } }, [settings.profileId, settings.datasetId])
  const current = useLiveQuery(() => result ? refreshLocalRetrieval(result) : null, [result, settings.profileId, settings.datasetId, settings.changePolicy?.epoch, clock])
  return <details className="conversation-search"><summary>資料と保存した会話をまとめて検索（文字検索）</summary><label className="field">検索語<input aria-label="資料と会話の検索語" value={query} maxLength={200} onChange={event => setQuery(event.target.value)} /></label><div className="form-grid"><label className="field">開始日<input type="date" value={from} onChange={event => setFrom(event.target.value)} /></label><label className="field">終了日<input type="date" value={to} onChange={event => setTo(event.target.value)} /></label></div><button className="secondary-button" disabled={busy || !query.trim()} onClick={async () => { setBusy(true); setError(''); try { setResult(await searchLocalContext(query, from, to)) } catch (failure) { setError(failure instanceof Error ? failure.message : String(failure)) } finally { setBusy(false) } }}>資料と会話を検索</button>
    {current && <><p className="muted">{current.notice}</p><p>取得・保存が確認できる範囲（完全な履歴ではありません）:</p>{current.coverage.map(range => <p key={`${range.kind}:${range.id}`} className="muted">{range.kind === 'library' ? '資料' : '端末内の会話'} · {range.fromDate}〜{range.toDate}</p>)}{current.hits.length === 0 && <p>指定期間の許可済み保存データに一致がありません。未取得履歴に依頼がないことは確認できません。</p>}{current.hits.map(hit => <article key={`${hit.kind}:${hit.id}`} style={{ marginTop: 14 }}><strong>{hit.kind === 'library' ? '資料' : '会話'} · {hit.title}</strong><p className="muted">{hit.provider} · {hit.author} · {hit.kind === 'library' ? '資料日' : '保存日時'} {hit.date}</p><blockquote style={{ whiteSpace: 'pre-wrap', overflowWrap: 'anywhere' }}>{hit.quote.slice(0, 3000)}{hit.quote.length > 3000 ? '\n（引用の先頭3000文字を表示）' : ''}</blockquote><small style={{ overflowWrap: 'anywhere' }}>出典 {hit.documentId} / {hit.id} · 版 {hit.revision} · 文字位置 {hit.start}〜{hit.end}（0基準）</small>{hit.kind === 'conversation' && onConversation && <button className="text-button" onClick={() => onConversation(hit.documentId)}>この会話を開く</button>}</article>)}</>}{error && <p role="alert">{error}</p>}
    <p className="muted">検索と引用表示だけでは外部AIへ送信しません。会話へ送る資料・記憶は別に本人が選択します。</p>
  </details>
}
