import { useEffect, useMemo, useState } from 'react'
import { changePolicyFor } from './change-set'
import { updateAIConnection } from './ai-connection'
import { createLocalActionController, type LocalActionOutcome } from './local-action-client'
import type { LocalActionDefinitionInput, LocalActionGateway, LocalActionInspection, LocalActionPrepared, LocalActionStatus, LocalActionWindow } from './local-action-types'
import type { Settings } from './domain'
const resultLabels={succeeded:'終了コード0で終了',failed:'実行失敗',timed_out:'制限時間で停止',canceled:'実行前に取消',unknown:'結果未確定'}
export default function LocalActionsView({settings,gateway}:{settings:Settings;gateway?:LocalActionGateway}) {
  const connection=gateway??(window as LocalActionWindow).michiLocalActions,controller=useMemo(()=>connection?createLocalActionController(connection):null,[connection]),policy=changePolicyFor(settings)
  const scopeKey=`${settings.profileId}:${settings.datasetId}:${policy.epoch}:${policy.sourcePermissionRevision}:${settings.aiEnabled}`
  const [view,setView]=useState<{scopeKey:string;status:LocalActionStatus|null;inspection:LocalActionInspection|null;prepared:LocalActionPrepared|null;outcome:LocalActionOutcome|null}>({scopeKey,status:null,inspection:null,prepared:null,outcome:null})
  const [title,setTitle]=useState('バージョン確認'),[executable,setExecutable]=useState(''),[cwd,setCwd]=useState(''),[argv,setArgv]=useState('["--version"]'),[schema,setSchema]=useState('{}')
  const [actionId,setActionId]=useState(''),[values,setValues]=useState<Record<string,Record<string,string|number|boolean>>>({}),[busy,setBusy]=useState(false),[notice,setNotice]=useState('')
  const active=view.scopeKey===scopeKey,status=active?view.status:null,inspection=active?view.inspection:null,prepared=active?view.prepared:null,outcome=active?view.outcome:null
  const chosen=status?.definitions.find(def=>def.id===actionId)??status?.definitions[0],params=chosen?Object.fromEntries(Object.entries(chosen.schema).map(([name,rule])=>[name,values[chosen.id]?.[name]??(rule.type==='string'?rule.enum[0]:rule.type==='number'?rule.min:false)])):{}
  useEffect(()=>{if(!controller)return;controller.clearAuthority();let active=true;void controller.refresh().then(status=>{if(active)setView({scopeKey,status,inspection:null,prepared:null,outcome:null})}).catch(error=>{if(active)setNotice(error instanceof Error?error.message:String(error))});return()=>{active=false;controller.clearAuthority()}},[controller,scopeKey])
  async function run(action:()=>Promise<void>){if(busy)return;setBusy(true);setNotice('');try{await action()}catch(error){setNotice(error instanceof Error?error.message:String(error))}finally{setBusy(false)}}
  function changed(){setView(previous=>({...previous,inspection:null,prepared:null,outcome:null}))}
  return <section className="card" aria-label="System Triggers PC操作"><h3>System Triggers：このPCの操作</h3>
    <p>本人が登録した実行ファイルと固定引数だけを、この画面から確認して実行できます。結果はタスクの完了やポイント加算に使いません。</p>
    {!controller?<p role="status">この環境ではPC操作を利用できません。Windowsアプリで設定してください。</p>:<>
      {!settings.aiEnabled?<div><p>APIキーなしで利用できます。AI処理の停止中はPC操作も停止します。</p><button type="button" className="secondary-button" disabled={busy} onClick={event=>{const native=event.nativeEvent;void run(async()=>{if(!(native instanceof Event)||!native.isTrusted)throw new Error('本人の有効化ボタンから操作してください。');await updateAIConnection(true);setNotice('AI処理を有効にしました。登録するPC操作を確認してください。')})}}>PC操作用にAI処理を有効にする</button></div>:null}
      {settings.aiEnabled?<button type="button" className="secondary-button" disabled={busy} onClick={event=>{const native=event.nativeEvent;void run(async()=>{if(!(native instanceof Event)||!native.isTrusted)throw new Error('本人の停止ボタンから操作してください。');await updateAIConnection(false);setNotice('AI処理とPC操作を停止しました。登録した操作は、再開後に本人が登録し直します。')})}}>AIとPC操作を停止</button>:null}
      <details open={!status?.definitions.length}><summary>固定操作を登録</summary><p>実行ファイルと作業フォルダーの絶対パスを指定し、引数を配列で登録します。たとえば、確認済みの node.exe に ["--version"] を渡すと、そのバージョンだけを表示します。</p>
        <label className="field"><span>操作名</span><input value={title} maxLength={120} disabled={busy} onChange={event=>{setTitle(event.target.value);changed()}}/></label>
        <label className="field"><span>実行ファイルの絶対パス</span><input value={executable} disabled={busy} placeholder="C:\Program Files\nodejs\node.exe" onChange={event=>{setExecutable(event.target.value);changed()}}/></label>
        <label className="field"><span>固定する作業フォルダーの絶対パス</span><input value={cwd} disabled={busy} placeholder="C:\Users\名前\Documents" onChange={event=>{setCwd(event.target.value);changed()}}/></label>
        <label className="field"><span>固定引数の配列（JSON）</span><textarea value={argv} rows={3} disabled={busy} onChange={event=>{setArgv(event.target.value);changed()}}/></label>
        <details><summary>型付き引数の選択肢</summary><p>任意のコマンド文字列やパス引数は指定できません。文字列は列挙した選択肢、整数は最小・最大、真偽値はtrue/falseだけを使えます。引数配列では {`{"param":"名前"}`} を指定します。</p><label className="field"><span>引数の定義（JSON）</span><textarea value={schema} rows={4} disabled={busy} onChange={event=>{setSchema(event.target.value);changed()}}/></label></details>
        <button type="button" data-local-action-configure="inspect" className="secondary-button" disabled={busy||!executable||!cwd||!settings.aiEnabled||!policy.aiChangesEnabled||policy.taskUpdate==='deny'} onClick={event=>{const native=event.nativeEvent;void run(async()=>{const input={title,executable,cwd,argv:JSON.parse(argv),schema:JSON.parse(schema)} as LocalActionDefinitionInput;const inspection=await controller.inspectFromUI(input,native);setView(previous=>({...previous,inspection,prepared:null,outcome:null}));setNotice('実行ファイルと引数を検証しました。まだ実行・登録していません。')})}}>登録する内容を検証</button>
        {inspection?<div><h4>今回登録する内容</h4><p>{inspection.definition.title}</p><p>実行ファイル：{inspection.definition.executable}</p><p>作業フォルダー：{inspection.definition.cwd}</p><pre>{JSON.stringify(inspection.definition.argv,null,2)}</pre><p className="muted">ファイル SHA256：{inspection.definition.sha256}<br/>確認期限：{new Date(inspection.expiresAt).toLocaleString('ja-JP')}</p><button type="button" data-local-action-configure={inspection.reference} className="primary-button" disabled={busy} onClick={event=>{const native=event.nativeEvent;void run(async()=>{const status=await controller.configureFromUI(inspection,native);setView({scopeKey,status,inspection:null,prepared:null,outcome:null});setNotice('固定操作を登録しました。実行する際には改めて確認します。')})}}>この実行ファイルと引数だけを登録</button></div>:null}
      </details>
      {status?.definitions.length?<div><h4>登録した操作</h4><label className="field"><span>操作</span><select value={chosen?.id??''} disabled={busy} onChange={event=>{setActionId(event.target.value);changed()}}>{status.definitions.map(def=><option key={def.id} value={def.id}>{def.title}</option>)}</select></label>
        {chosen?<><p className="muted">{chosen.executable}<br/>版 {chosen.revision} / SHA256 {chosen.sha256.slice(0,12)}</p>{Object.entries(chosen.schema).map(([name,rule])=><label className="field" key={name}><span>{name}</span>{rule.type==='string'?<select value={String(params[name])} disabled={busy} onChange={event=>{setValues(previous=>({...previous,[chosen.id]:{...previous[chosen.id],[name]:event.target.value}}));changed()}}>{rule.enum.map(value=><option key={value}>{value}</option>)}</select>:rule.type==='number'?<input type="number" min={rule.min} max={rule.max} step={1} value={Number(params[name])} disabled={busy} onChange={event=>{setValues(previous=>({...previous,[chosen.id]:{...previous[chosen.id],[name]:Number(event.target.value)}}));changed()}}/>:<input type="checkbox" checked={Boolean(params[name])} disabled={busy} onChange={event=>{setValues(previous=>({...previous,[chosen.id]:{...previous[chosen.id],[name]:event.target.checked}}));changed()}}/>}</label>)}
          <div className="change-set-actions"><button type="button" className="secondary-button" disabled={busy||!status.enabled} onClick={()=>void run(async()=>{const prepared=await controller.prepare(chosen.id,params);setView(previous=>({...previous,prepared,outcome:null}));setNotice('内容を確認してください。まだ実行していません。')})}>今回の実行内容を確認</button><button type="button" data-local-action-configure={`remove:${chosen.id}`} className="secondary-button" disabled={busy} onClick={event=>{const native=event.nativeEvent;void run(async()=>{const status=await controller.removeFromUI(chosen.id,native);setView({scopeKey,status,inspection:null,prepared:null,outcome:null});setNotice('この固定操作の登録を取り消しました。')})}}>この操作の登録を取り消す</button></div></>:null}
      </div>:null}
      {prepared?<div aria-label="今回のPC操作の確認"><h4>今回だけ実行する内容</h4><p>実行ファイル：{prepared.review.executable}</p><p>作業フォルダー：{prepared.review.cwd}</p><pre>{JSON.stringify(prepared.review.argv,null,2)}</pre><p>1回だけ実行します。実行時間は最大30秒、結果出力は最大64KBです。</p><p className="muted">確認期限：{new Date(prepared.review.expiresAt).toLocaleString('ja-JP')} / 内容 {prepared.review.digest.slice(0,12)}</p>{!outcome?<button type="button" data-local-action-approve={prepared.reference} className="primary-button" disabled={busy||!settings.aiEnabled} onClick={event=>{const native=event.nativeEvent;void run(async()=>{const outcome=await controller.executeFromUI(prepared,native);setView(previous=>({...previous,outcome}));setNotice(outcome.receiptSaved?'PC操作の結果を保存しました。':'PC操作の結果を受け取りました。アプリの履歴保存を再試行してください。')})}}>この内容だけを承認して実行</button>:null}</div>:null}
      {outcome?<article><h4>{resultLabels[outcome.result.status]}</h4><p>終了コード：{outcome.result.exitCode??'未確定'}{outcome.result.outputTruncated?' / 出力は上限で省略しました。':''}</p><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{outcome.result.output||'出力なし'}</pre>{!outcome.receiptSaved?<button type="button" className="secondary-button" disabled={busy} onClick={event=>{const native=event.nativeEvent;void run(async()=>{const retried=await controller.retryReceiptFromUI(outcome.result,native);setView(previous=>({...previous,outcome:retried}));setNotice(retried.receiptSaved?'履歴を保存しました。PC操作は再実行していません。':'結果を受け取り済みですが、アプリの履歴保存は未確認です。')})}}>受け取った結果の履歴保存を再試行</button>:null}</article>:null}
      <p className="muted">{status?.notice}</p><button type="button" className="secondary-button" disabled={busy} onClick={()=>void run(async()=>{const status=await controller.refresh();setView(previous=>({...previous,status}));setNotice('登録と実行履歴を更新しました。')})}>登録と履歴を更新</button>
      {status?.results.length?<details><summary>端末に保存した実行結果（{status.results.length}件）</summary>{status.results.map(result=><article key={result.requestId}><strong>{resultLabels[result.status]}</strong><p>{new Date(result.completedAt).toLocaleString('ja-JP')} / 終了コード {result.exitCode??'未確定'}</p><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{result.output||'出力なし'}</pre></article>)}</details>:null}
    </>}
    <p role="status">{notice||(busy?'確認しています…':'')}</p>
  </section>
}
