import {useState} from 'react'
import type {LocalActionController} from './local-action-client'
import type {LocalActionAutomationInspection,LocalActionDefinition,LocalActionStatus} from './local-action-types'
export default function LocalActionAutomationView({definition,params,controller,status,onStatus}:{definition:LocalActionDefinition;params:Record<string,string|number|boolean>;controller:LocalActionController;status:LocalActionStatus;onStatus:(status:LocalActionStatus)=>void}){
 const [task,setTask]=useState(true),[session,setSession]=useState(false),[lowRisk,setLowRisk]=useState(false),[days,setDays]=useState('1'),[rate,setRate]=useState('1'),[inspection,setInspection]=useState<LocalActionAutomationInspection|null>(null),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false)
 const saved=definition.automation,runs=status.runs?.filter(r=>r.actionId===definition.id).length??0
 async function run(work:()=>Promise<void>){setBusy(true);setNotice('');try{await work()}catch(e){setNotice(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
 return <section aria-label="PC操作の自動実行"><h4>イベントに合わせた実行</h4><p>{saved?`${saved.lowRisk?'条件内で自動実行':'毎回確認'} / ${saved.events.join('・')} / 期限 ${new Date(saved.expiresAt).toLocaleString('ja-JP')} / この1時間 ${runs}/${saved.maxRunsPerHour}回`:'自動実行は未許可です。'}</p>
 <p>上で選んだ引数を固定します。過去のイベントをまとめて実行しません。PC操作の結果からタスクを完了したり、ポイントを増やしたりしません。</p>
 <label><input type="checkbox" checked={task} onChange={e=>{setTask(e.target.checked);setInspection(null)}}/>タスクを本人が完了したとき</label><label><input type="checkbox" checked={session} onChange={e=>{setSession(e.target.checked);setInspection(null)}}/>作業区間を記録したとき</label>
 <label className="field">有効日数（最大30日）<input type="number" min="1" max="30" value={days} onChange={e=>{setDays(e.target.value);setInspection(null)}}/></label>
 <label className="field">1時間の実行上限（最大6回）<input type="number" min="1" max="6" value={rate} onChange={e=>{setRate(e.target.value);setInspection(null)}}/></label>
 <label><input type="checkbox" checked={lowRisk} onChange={e=>{setLowRisk(e.target.checked);setInspection(null)}}/>この固定操作は低リスクと確認したので、許可した条件内だけ確認なしで実行する</label><p>チェックしない場合は60秒間の確認カードだけを作り、本人が承認するまで実行しません。</p>
 <button type="button" className="secondary-button" disabled={busy||!status.enabled||!task&&!session} data-local-action-configure={`automation-inspect:${definition.id}`} onClick={e=>{const native=e.nativeEvent;void run(async()=>setInspection(await controller.inspectAutomationFromUI({actionId:definition.id,events:[...(task?['task.completed' as const]:[]),...(session?['work_session.logged' as const]:[])],params,lowRisk,expiresAt:Date.now()+Number(days)*86400000,maxRunsPerHour:Number(rate)},native)))}}>この条件を検証</button>
 {inspection?<article><h4>今回だけ許可する条件</h4><pre>{JSON.stringify(inspection.automation,null,2)}</pre><p>{definition.executable}</p><button type="button" className="secondary-button" disabled={busy} data-local-action-configure={inspection.reference} onClick={e=>{const native=e.nativeEvent;void run(async()=>{onStatus(await controller.configureAutomationFromUI(inspection,native));setInspection(null);setNotice('このイベント・固定引数・期限・回数だけを許可しました。')})}}>この条件だけ実行を許可</button><button type="button" className="secondary-button" onClick={()=>setInspection(null)}>確認を閉じる</button></article>:null}
 {saved?<button type="button" className="secondary-button" disabled={busy} onClick={()=>void run(async()=>{onStatus(await controller.revokeAutomation(definition.id));setInspection(null);setNotice('この操作のイベント実行を停止しました。')})}>この操作の自動実行を停止</button>:null}
 <button type="button" className="secondary-button" disabled={busy} onClick={()=>void run(async()=>{onStatus(await controller.revokeAutomation(null));setInspection(null);setNotice('すべてのイベント実行を停止しました。')})}>すべての自動実行を停止</button><p role="status">{notice}</p></section>
}
